In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("Datasets/Originals/email.csv")
df

     Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [3]:
df.shape

(5572, 2)

In [4]:
df.isna().sum()

Category    0
Message     0
dtype: int64

In [5]:
df['Category'].value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [6]:
len(df['Message'].unique())

5157

In [7]:
df = df.drop_duplicates()

In [8]:
df['charCount'] = df['Message'].str.len()
df['wordCount'] = df['Message'].str.split().str.len()
# df['sentenceCount'] = df['Message'].str.count(r'[.!?]') + 1
df["digitCount"] = df["Message"].str.count(r"\d")
df["urlCount"] = df["Message"].str.count(r"http|www")
df["currencyCount"] = df["Message"].str.count(r"£|\$|₹")
df["exclamationCount"] = df["Message"].str.count("!")
df.groupby("Category")[["charCount","wordCount","digitCount","urlCount","currencyCount"]].mean()

C:\Users\ASUS\AppData\Local\Temp\ipykernel_13196\314683738.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['charCount'] = df['Message'].str.len()
C:\Users\ASUS\AppData\Local\Temp\ipykernel_13196\314683738.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['wordCount'] = df['Message'].str.split().str.len()
C:\Users\ASUS\AppData\Local\Temp\ipykernel_13196\314683738.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["digitCount"] = df["Message"].str.count(r"\d")
C:\Users\ASUS\AppData\Local\Temp\ipykernel_13196\314683738.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["urlCount"] = df["Message"].str.count(r"http|www")
C:\Users\ASUS\AppData\Local\Temp\ipykernel_13196\314683738.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["currencyCount"] = df["Message"].str.count(r"£|\$|₹")
C:\Users\ASUS\AppData\Local\Temp\ipykernel_13196\314683738.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["exclamationCount"] = df["Message"].str.count("!")

           charCount  wordCount  digitCount  urlCount  currencyCount
Category
ham        70.869353  14.239814    0.296723  0.000443       0.005314
spam      137.118565  23.659906   15.329173  0.154446       0.411856

In [9]:
spamOnly = df[df['Category']=='spam']

In [10]:
spamOnly

,Category,Message,charCount,wordCount,digitCount,urlCount,currencyCount,exclamationCount
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,155,28,25,0,0,0
5,spam,FreeMsg Hey there darling it's been 3 week's n...,147,32,4,0,1,2
8,spam,WINNER!! As a valued network customer you have...,157,26,19,0,1,3
9,spam,Had your mobile 11 months or more? U R entitle...,154,29,13,0,0,1
11,spam,"SIX chances to win CASH! From 100 to 20,000 po...",136,26,22,0,0,1
...,...,...,...,...,...,...,...,...
5537,spam,Want explicit SEX in 30 secs? Ring 02073162414...,90,16,21,0,0,1
5540,spam,ASKED 3MOBILE IF 0870 CHATLINES INCLU IN FREE ...,158,33,14,0,2,0
5547,spam,Had your contract mobile 11 Mnths? Latest Moto...,160,28,2,0,0,1
5566,spam,REMINDER FROM O2: To get 2.50 pounds free call...,147,28,5,0,0,0
5567,spam,This is the 2nd time we have tried 2 contact u...,160,30,21,0,1,1

In [11]:
spamOnly.shape

(641, 8)

In [25]:
spamWords=set()
for i in spamOnly.Message:
    # print(i)
    # print("\n")
    singleLine = i.split(' ')
    for j in singleLine:
        spamWords.add(j)
    
print(spamWords)

{'wish.', 'RECPT', '09066368327', 'Burger', 'Age', '400', 'Why', '150ppm.', 'vodafone', '88066', 'logo&pic', '8.', '4403LDNW1A7RW18', 'sufficient', '83332.Please', 'CDs', 'ONLY', '?', 'gold', 'EXORCIST,', 'java', 'tonights', '02/06/03!', "month's", 'message.', 'texts/weekend', 'responding', 'asked', 'next', 'u!', 'care', 'came', 'these', 'RECEIVE', '5free.', '0796XXXXXX.', 'ENTER', 'gettin', 'Lions', '24hrs.', 'Questions:', '81151', '£1000.', '(18+)', 'M39M51', 'friends.', 'www.ringtones.co.uk,', 'BOX42WR29C,', 'Txt', 'costs', '-call', 'XCHAT.', 'Phony', 'EH74RR', 'Ltd.', 'HAVE', 'PHONE', 'Orange.', '09041940223', '0906346330.', 'selected', 'WILL', '150p/text', '09050090044', '150p/MsgrcvdHG/Suite342/2Lands/Row/W1J6HL', 'Hottest', 'simply', 'legitimat', 'driving', '£5000', 'smart..Though', 'A', '85023', '0871-4719-523', 'missed', '3mins', 'MINS.', 'Mnths?', 'loyalty.', 'prize', 'msg', 'OUT', 'Nick,', '2006', 'Oranges', 'login', 'thought', 'mobs', '1-month', '09095350301', '"MIX"', 'blow', 'discount', 'operator', 'Mob', '(Send', 'ACTION', 'HOTMIX', 'sending', 'Camcorder', 'Code', 'Sony', '145', 'vouchers!', 'Sullivan', 'txt>', 'GBP/week!', 'games!', 'loyal', 'games,', 'SonyEricsson', 'UNLIMITED', '07815296484', 'invited', 'out', 'further', '6031', '8077', 'credit', '?.', 'UK-mobile-date', 'Monthly', 'extra', 'http://www.bubbletext.com', 'fones,', 'NO-762', '81618-?3', 'bid,', 'Dont', 'woman', 'him:', '150PPM', 'ENTER.', 'can', 'Only', 'Hello', 'callcost', 'e.', 'www.music-trivia.net', 'quote', 'rental?', 'moby', 'FREE*', '0871212025016', 'NO-440', 'AWAITING', 'opinions.', '89080', 'no,', 'call2optout/N9DX', 'www.phb1.com', 'town.', 'subsequent', 'UKs', 'PoBox75LDNS7', '"3000', 'BOX385', 'Kingdom.', 'service.', 'Box1146', 'POBOXox36504W45WQ', 'okmail:', 'hotels', 'help:08700469649.', 'connected', '2StopTxt', 'Congrats', 'Club:', 'his', '0578', 'cumin', 'yo-Here', 'TheDailyDraw)', 'WWW.ASJESUS.COM', '150ppm', '449050000301', 'area?', '09065989182', 'mins/texts.', 'Good', '08719181259', '(Book', 'lover', 'close.', 'E', 'rental', 'stop.', '4742', 'POBox', '2stoptxt', '7', 'yo', 'T-Mobile.', 'Hot', 'XXUK', 'www.win-82050.co.uk', '(£4.50)', 'YMCA', 'Strokes!', 'Poly', 'Weekly', 'Rayman', 'g696ga', 'Awarded', "B'tooth*.", 'FREE', 'CR9', 'last', 'question:', 'SLEEPINGWITH,', '4.49/month', 'bill', 'skills', 'content', 'Flirt!!', '07099833605', 'Try', '09061701461.', '45', 'Nyt.EC2A.3LP.msg@150p', 'quoting', 'mates.', 'Stockport,', 'toClaim.', 'Other', '09061743810', 'sound', 'chg', 'Games,', '2day', '10th', 'latest', 'released', 'offers.', '09065394514', '1/3.', 'TCs', 'mre', '542', 'who', 'goals/team', 'good', 'away,', 'FML,', 'Use', 'XXXXXX', '12', 'CASH,', 'Woods', '08708800282', '"Divorce', "it's", 'you.', 'Handset?', 'July.', 'Wet', 'stamped', 'accommodation', 'services.', 'Ab..,', 'Mila,', 'CDGT', 'AM', 'to', 'SOIREE', '£79', 'poly/true/Pix/Ringtones/Games', 'ave', 'here', 'HARRY,', 'ip4.', '07808', '69855,', 'another', '08715203656', 'CUST', 'WANT', 'between', 'ENGLAND', '£900', 'missing', '2nite', 'date', 'Years', 'K718.', '087123002209am-7pm.', 'subject', 'continued', 'ansr', 'SUMMER', 'FRND', 'Hack', '310303.', 'BOX139,', 'SAE,', 'POST,', 'us', 'gift.', 'horniest', 'chat?Im', 'M95.', 'MUST', 'changed!', 'lines', "C's", 'won', 'Hi,', 'Linerental', 'calls!', 'DONT', 'should', '26/11/04', 'results', 'compare', 'Ldn,', 'GENDER', 'well', 'Voda', 'Easter', 'private', 'person;', '08717168528', '62468', 'DOT', 'Shopping', 'chances', 'female', '09065394973', '#150', 'mates,', 'network.', 'smashed', '1.', 'Hard', '08700621170150p', 'Black', 'WINNER!!', 'xxxmobilemovieclub.com?n=QJKGIGHJJGCBL', 'feeling', 'Text82228>>', 'Y87.', "T's", '83049.', 'August', '16+', 'adult', 'Games', 'Call', 'web2mobile', 'Ring', 'Upd8', 'Verify', 'HI!!!"', 'service', 'join', 'XMAS', 'accessible.', '1013', 'Jamster!', 'collection.', 'sun0819', 'After', '750', 'polys:', 'click', 'FINAL', 'PO19', '*turn*', 'prize.', 'Birthday?', 'CALL', '83383.', 'subscriber', 'HEART', 'pleased', '09064018838.', '08448350055', '08718727870.', 'tones2you.co.uk', '30', '08006344447', 'Jordan,', 'AWARD!', 'Arrow', 'things', '24/7MP', 'POBOX84,', 'TsCs', '09058094599', 'Tom,', 'cross', 'DIGITAL', "Today's", 'renewed', 'tariffs', '£1.50ea.', 'CustomerCare', 'www.4-tc.biz', 'now!SKY', '300603', 'REWARD', 'TEXTCOMP', 'currently', '+', '£1million', 'goodies!', '26th', 'Gnarls', 'Msg', 'Bluetooth!', 'SPEEDCHAT', 'Asian', '09058099801', 'because', 'year.', 'LISTENING', '6WU', 'Triple', '(quizclub', '150p.', 'doubles', 'Wanting,', 'fun?', 'Ref:9280114', 'Warner', 'being', 'MOBNO', 'DIRTY', 'purchase', 'recent', 'Last', 'TCR/W1', '£350!', '3030.', 'console.', 'R836.', 'Sept', 'Uve', '150p/Msg', 'really', '08712466669', 'R*reveal', 'Married', 'inviting', 'NOW1!', '2nite!.', 'PRIVATE!', 'NoWorriesLoans.com', 'voicemail.', 'LIFE', 'Chat', 'Ltd,', 'For', 'died', '07946746291/07880867867', 'Loan', 'PICSFREE1', 'stolen,', '08000407165', '69911(£1.50p.', 'not', 'ac/smsrewards', 'me?', '£1.', 'records', 'before', '09066380611', 'book', 'Nokia/150p', 'Day.', 'YES', 'rate)', 'subscribed', '5/9/03', '2WU.', 'challenge', '434', 'WeddingFriend', '09090204448', 'loan?', 'married', 'www.SMS.ac/u/goldviking', 'Information', 'landline', 'us.', 'pole.', 'WELL', 'moby.', 'info:www.100percent-real.com', 'World', "08452810075over18's", 'RALLY', '9996.', '08714712412', 'Number:', 'str*', 'removal', 'My', 'pics.', '07XXXXXXXXX', 'Rodger', 'Cant', 'A£1.50', '30s', 'ur', '2stop', '80488', 'folks', 'vary', '07808726822', "You'll", 'living', 'night', 'chik.', 'Have', 'Find', 'TXT', 'is:', 'Date', '08701417012', 'Tickets', '2C', 'wk.', 'instructions', 'hot', 'Did', 'fromm', 'lets', '£3', 'thinks', 'services', 'Enjoy', 'tattoos?', 'sport,', 'guaranteed', 'could', 'ree', '7250', 'shortly', 'British', 'URGENT', 'TheMob>Yo', 'hotel', 'Just', 'colours!', 'badass', '81010', '£600.', 'sexy,', 'BIG', "It's", 'IT', '1)', 'keyword', 'toilet', 'HG/Suite342/2lands', '09066382422', '10/06/03!', 'will!', 'shopping', '28th', 'SplashMobile:', 'promised', 'profit', 'saucy', 'Offer:', 'porn!', 'Hello.', 'text.', 'season', '(100p/SMS)', 'collected.', 'auction.', 'HG/Suite342/2Lands/Row/W1J6HL', 'XCHAT,', '£50award.', 'previous', 'website.', '88039', 'BluetoothHdset', 'got', 'calling!', 'ever', 'mins.', '83370.', 'logos', '139,', 'darkest', 'wining', '£1000CALL', 'MESSAGE**Thanks', 'Cup', 'may', 'CustCare:08718720201', 'award', '08701237397', 'ones', 'rcvd.', 'true', 'polyH', 'TO', 'iPOD', 'LISTEN', 'Libertines', 'contract', 'Msgs', 'seem', 'pause', 'textoperator', 'box245c2150pm', '"ADP"', '89034', 'KING', 'LA32WU.', 'inc', '0A$NETWORKS', '08709222922.', 'noline', '125gift', 'fixed', 'send', 'Jeri', '5', 'settings.', 'Echo', 'SPAM', 'Day,', 'bulbs', 'men.', 'TCs,', "weekend's", '08448714184', 'Classic', 'EASTENDERS', '+£400', 'G', 'lucozade.co.uk/wrc', 'St', '83600', 'po', 'x-net', 'action.', 'MARSMS.', '87077:', 'unsubscribe', 'name', 'Great', "we'll", 'M221BP.', '18+only', 'premium', 'Summer', 'Who', 'CREDIT', 'Us', 'Strip', 'membership', 'Customer', 'Gay', '09061749602', '150p/meg.', 'Santa', 'May', '-)', 'I', 'dont', 'MSG*', 'recd@thirtyeight', 'rentl.', 'readers!', 'optout', 'BOX', 'dating:i', 'United', 'into', "won't", 'call:', 'BILL.', 'details!', 'regard', 'SHOW', 'be', '32000', 'AOM', '1/08/03!', 'been', 'ZOUK', 'January', 'Camcorder?', 'Cool-Mob', 'find', '85', '2KBSubject:', 'MonthlySubscription@50p/msg', 'YES.', '69101.', 'house', "UNICEF's", '09058095107', 'Simply', 'singles', '150', '2.50', 'draw', '80062.', 'VAT', 'cust', '326', 'M6', 'Sppok', 'inc)', 'www.ringtoneking.co.uk!', 'activate', 'BREATHE1', 'callback,', 'weekly', 'Xmas', 'Jamz', 'ONE', 'for', 'POST', 'NOK', 'mobile.', 'wk!', 'SPECIALE', 'nokia', 'K52', 'soundtrack', '81303.', '06.05.05', 'OFFICE', 'say', 'in!', '100', '44', 'Mailbox', 'Direct', '-sub', 'new', 'OVER', 'Welcome', 'Pic', 'pls', 'SAM', 'fans', 'FOR', 'age16.150ppermessSubscription', 'W111WX', 'nos', '13/10/04', 'TOTALLY', 'efreefone', 'Gsex', '300p', 'O', 'sticky', 'high,', 'saturday', 'Nokia', 'MOAN', 'ON', 'wedding', '£2.50', 'flights', 'issues', 'Well', '10ppm.', 'HMV', '02072069400.', 'President?', 'Nookii', 'off', 'reward!', 'yet.', 'posh', 'LS278BB', 'NAME', 'anytime', 'VPOD', '£5', '42478', 'subscribers', '13/4/04.', 'contact', 'Bluetooth', '41685', 'call.', 'follows,', 'do.Interested?', 'is?', 'help?', 'Cs', 'Mob!', 'price', 'friend', 'Min', 'Cash.', 'allow', 'A.', 'were', 'help', 'tried', 'quiz', 'selling', 'using', 'increments.', 'get', 'BOX95QU', 'processed...', 'ORANGE', 'ShrAcomOrSglSuplt)10,', 'Boltblue', 'news', 'dark', 'CRAZYIN,', 'FIND', '2025050', 'look', 'w8in', 'week!', 'back', 'Bloomberg', 'Calls', 'Yours', '80062', 'thanks', 'address', '12mths', 'Phone', 'proze', 'weekend!)', 'digits)', 'Send', '28', 'welcome.', 'TONEXS', 'too', 'avble.', '9061100010', 'months?', '30th', 'OUT.', 'These..', '-PLS', 'phones.', '69696', 'WC1N', '[sic]', 'Oh', 'MUNSTERS,', '02073162414', 'sent', 'MIN', 'music,', 'Tsunami', '08712405020.', 'great', 'THIS', 'you,', '£1.50pmmorefrommobile2Bremoved-MobyPOBox734LS27YF', 'weeks>', 'future', 'box403', 'K61.', 'here>>', 'Energy', 'Ben', '69969', '4goten', 'Delivery', 'yrs', 'Helpline', 'collect', 'CLUB', '£33:50', 'by', 'LUCY', 'Free,', 'phone!', '6days,', 'HIDE', 'Termsapply', 'Orange', 'Amanda', '£3.00', 'http://careers.', 'Red', '5226', 'Content', 'ac', '+447797706009', 'now!SavaMob-member', 'nasty', 'crazy', 'yourself.', 'MK45', 'Rental', 'info@ringtoneking.co.uk', 'PIX', 'LookAtMe!,', '1st4Terms', 'simple', 'Luck!', 'advise', 'Want', '86688', 'Hey', 'four', 'chrgd@50p', '2morro', 'news.', 'MobcudB', 'sounds', 'NUMBER,', 'this', 'dream', 'msg:', 'lifetime!', 'ADDAMSFA,', 'there', 'Algarve', 'provided', 'AND', 'met', 'X49.Your', '83039', '18', '80608.', 'days', '16+only', 'Calling!', 'receivea', 'dating?', 'fgkslpoPW', 'I.', 'goto', '2nite?', '09058094594', 'Ldn', "RCT'", '74355', 'types', 'Text', 'Polo', 'goldviking', 'December', 'Choose', "1000's", '3MOBILE', 'leave', 'cinema', 'www.80488.biz', 'Ibiza', 'guarantee', 'PIX!', 'needs', '2p', 'luck!', 'T&CsC', '09061790121', '07090298926', '09064017295', 'pass', 'QlynnBV', 'shows', '(std', 'Tones,', 'ENG', 'only.', 'Cha', '50p', 's,', "you've", 'someone', '2moro', 'delivery.', 'more!', 'Movie', 'ALL', 'onto', 'winner', 'believe', 'stop?txtStop', "'help'", 'charts', '1327', 'live', 'Service', 'marketing', 'uk!', 'Tel', '6669', 'mins?', 'CC', 'Bray,', 'GMW', 'See', 'b4190604,', 'Euro2004', 'no', 'KEEP', 'Im', "VALENTINE'S", '08000930705', 'SF', 'picked', 'Dates', '5WE', 'all', 'up', 'FLAG', 'various', 'charge', '£50-£500.', 'ipod.', 'PoBox45W2TG150P', '0871750.77.11!', 'only!', "C's.", 'Calls£1/minMobsmore', 'video/pic', '8000930705', 'more', 'free', '88888.', 'www.gamb.tv', 'Motorola', '!', 'Alfie', 'waiting', 'Code:', '"Crazy"', 'Stereophonics,', 'held?', 'mymoby.', '2007', 'yards', '02', 'guys', 'OptOut', '0789xxxxxxx.', 'Kath.', '£1250', 'babe', '5we.', '32323.', 'sport', 'Double', 'games', 'AOM,', 'vouchers-Text', '69200', 'Goal!', 'FREE!', 'Cheap', ':getzed.co.uk', 'go2', 'Nyt.', '40411', 'ans', 'call2optout/!YHL', 'name,', 'Jordan!Txt', '177.', 'EURO2004', 'ok', 'London', 'five', 'enjoy!', 'New', '£2,000', 'tddnewsletter@emc1.co.uk', 'getting', '.', 'me', 'night?', 'SAE', 'bout', '88039.SkilGme.TsCs087147403231Winawk!Age16+£1.50perWKsub', 'Jordan!', 'CUTE', '4info', 'fit', '09066364349', '28,', '89693.', 'fancy', 'left', 'www.SMS.ac/u/bootydelious', 'go', 'over', 'Ringtone¡', 'special-call', 'hope', '87239', 'Shop', 'G.B.', 'hava', 'When', 'partner?', 'outbid', 'C)', '42810', 'rply', "Moon's", 'way.', 'Subs', 'renewal', 'winner!', 'Drop,', '1,2', '1Winaweek,', 'Sol', '£5000.00', 'JANE', 'Congratulations!', '08715205273', 'Henry', 'Inclusive', '84199.', 'Club.', 'SEXYCHAT', '09064019014', 'National', '60p/min.', 'straight', '09066358152', 'Help?', 'visionsms.com', 'real', 'FANTASTIC', 'holder', 'Sam', 'WOW!', 'CHATLINES', 'OF', 'supply', 'garden', 'free!', 'passion', '09066364589', 'tone,', 'male', '731', '£350', 'No.', 'lonely,', 'M227XY.', 'Statement', 'cost', 'STOP.', 'cam', 'message', '8552', 'trial', 't&c', '09099726481', '08712460324', 'GBP', 'Him', 'Sony,', 'cruise', 'so,', 'Quiz!', '08719180219', '09061213237', 'fink', 'trebles!', 'Village', 'horny,', '29/10/0', '1000', 'starting', 'credited', '5)', 'order', '5WB', '88877>FREE', 'STOPBCM', 'tones', '3)', "U've", 'funk', 'TnC', 'faster', 'u?', 'babes', '6,', 'flirting', 'refused?', 'unsubscribe.', '69888', 'PARIS', '18+6*£1.50(moreFrmMob.', 'going', 'Hi.', '1ER', 'LookAtMe!:', '3.', 'Invaders', 'So', 'thesmszone.com', 'paying', 'FreeMsg:', 'special.', "T's&C's", 'valued', 'win150ppmx3age16', 'rpl', 'end,', 'INC', 'Todays', 'to?', 'Incorrect?', 'late', "don't,", '09064015307', 'AG', 'show', 'disaster', 'BOX97N7QP,', 'night!', 'England', 'ppt150x3+normal', 'BCM1896WC1N3XX', 'http://www.wtlp.co.uk/text.', '2', 'YOU!', 'www.areyouunique.co.uk', 'everyone', 'OUR', 'give', 'definitely', 'Stop', "uk's", 'TBS/PERSOLVO.', '1.5p/min', 'country', '09058094454', '450p', '09050000332', 'footy', '“Harry', 'abuse???', 'colour', 'yet', 'Help08714742804', 'will', '21/m', 'in', 'Shinco', '0776xxxxxxx', 'messages-Text', '83118', 'Uks', 'xt', 'Gr8', '86888', 'connect', 'No:', 'created', 'G2', '0870737910216yrs', 'Landline.', 'think???', '2005.', 'tomorrow', '10am-9pm', 'PO', '114/14', 'place', '09701213186', 'backdoor', 'tour?', 'GUARANTEED!', 'POBox36504W45WQ', 'Try:WALES,', 'Quiz.', 'months', 'SURPRISE', 'a', '1225', 'Join', 'come', 'think', 'compensation', 'Bought', 'following', 'calls', 'CR01327BT', 'begin.', '09065989180', 'holiday', 'user', 'Blind', 'Today', 'Buy', 'maniac?', 'ends', 'From:', 'Latest', 'worth', '***************', 'ignore', 'WINNER!', '(flights', 'How', 'Collect', '3Lions', 'PARK', 'widelive.com/index.', '09058094507', 'rooms', 'BEFORE', '8883', '5249,', 'Teletext', 'collection', 'havin', 'floppy...', 'these.', 'Holder,', 'thousands', '087187272008', 'Hoody', 'format', 'minded', 'Back.', '0207', '20p', 'Sugababes,', 'X', 'Matrix3,', 'TXTAUCTION!', 'SING', 'Future', 'Moby', 'T.', 'Large', "I'd", 'Requests', 'visit', 'Adrian', 'calling', 'buddys.', 'Saristar', 'rcv', 'read', 'companies', 'Someone', 'notxt.co.uk', '08717205546', 'credit,', 'mobiles.', 'www.Ldew.com', 'Save', '946', 'camcorder.', 'Rate.', 'Claim.', 'now!nyt.', 'Records', 'ten', 'DIS', 'Heroes,', 'around', 'quality', 'POLY#', 'Valid12hrs', 'TOP', 'OK', '07786200117', 'HG/Suite342/2Lands', '87131', 'W4', 'spree,', '08717890890£1.50', 'Give', 'Check', 'standard', 'Player', 'content.', 'SUPER', 'questions.', 'TheMob>Hit', 'Its', 'you!', 'reference', 'take', 'v', '1x150p/wk', 'listen', 'finally', '1)Unbreakable,', 'sign', 'Game', '49557', 'NOKIA6600', 'Panasonic', 'CARD', 'parties...', 'presence', 'DENA', 'eg', '69669', 'tariffs.', '09065171142-stopsms-08', 'POBOX114/14TCR/W1', 'enough?', 'complementary', 'Flag', '£75,000.', 'won.', 'SiPix', 'Wanna', 'fun', 'TV.', 'you!To', '09061104283', 'unsubscribed', 'Come', 'IMPORTANT', '85.', 'gr8prizes', 'members', '&XXX', 'Cashbin.co.uk', 'door,', 'recieve', '200', 'which', 'guys.', 'CLAIM', 'wiv', 'completely', 'till', '&Cs', '123', 'Home', '18p/txt', '08719899229', 'TULIP', '08717111821', 'videosounds+2', '69866.18', 'laid', 'pic?', '08718730666', 'notified', 'CM', '087104711148', 'Xmas?', 'BabyGoodbye', 'monos', '150p/day,', 'now.', '07123456789', 'Hubby', 'ya', 'Text:', 'that', 'call09050000327.', 'ans.', 'G.', 'Randy,', 'med', '80082', 'FreeMsg>FAV', '(mob', 'how', '10p', 'Dozens', 'flirt?', 'ec2a.', 'choice.', 'TC-LLC', 'ordered', '£250k', '087018728737,', '0871-872-9758', 'Email', '31/10/04', 'posts', '89555', 'Msg:', 'coincidence?', 'sexual', 'Remove', '09058094455', 'UK,', 'Single?', 'secretly', 'Babe:', 'wml?id=820554ad0a1705572711&first=true¡C', '£100,000', 'LE', 'fantastic', 'E.G.23F.', 'Landline', '9153.', 'special', 'stories', 'mob.', '3qxj9', 'Phoenix', 'charge)', 'claim,', 'Provided', 'used', 'Draw.', 'ADAM', 'glad,', 'tv', '69698', 'cum', '80122300p/wk', 'www.txt43.com', 'nights,', 'much', 'June', '(Get', 'Free-message:', 'Won.', '25', 'www.getzed.co.uk', "let's", 'C-Red', 'seeds', 'POLYPHONIC', 'revealed.', '08001950382', 'TsCs087147403231Winawk!Age16', 'in?', '12hrs', 'day!', 'COLLECT', '4mths', 'phone', 'MESSAGE', 'STOP?', 'www.clubmoby.com', '78', 'SUBPOLY', 'charity.', 'shortly.', 'Reminder:', 'fraction', '09063458130', '150p/tone', 'texting', 'SHOULD', 'month.', 'W1J', 'C.', 'Voucher', 'Duchess', '150pm.', 'Prize,', 'age16', 'Plyr.', 'Order', 'EuroDisinc', '08712404000', 'Ref:9307622', 'pence', 'stopCost', 'Lucozade', 'never', 'PHP', 'wallpaper', 'card', '85069', 'BCM4284', 'potential', 'PRIZEAWAITING', 'competition', 'Goto', 'ready', 'T&CsBCM4235WC1N3XX.', '89693', 'matches.', 'include:', 'stars', 'Tones', 'when', 'TV', 'term', 'Book', 'alfie', 'CAMERA', 'subscriber,', 'Log', 'money', 'global', '450pw', 'flag', 'request', 'wow', 'TONE.', '83355!', 'Hardcore', 'T', 'Low-cost', 'PoBox12n146tf15', 'call2optout/HF8', 'Summers', '10am-7pm', 'the', '1956669', 'store', '4.50.', '07973788240', 'Kit', 'area', '250', '50%', 'meal', 'here!', 'tons', 'VU', 'Cost£1.50/pm,', '01223585236', 'charged@150p/msg.2', 'SavaMob,', 'YESTERDAY', 'gaytextbuddy.com.', 'Delivered', '08712402972', 'Bx', 'Back', 'www.dbuk.net', 'and', '150p', '09050000878.', 'wid', 'T&C:', 'soon,', 'wanna', 'had', 'benefits.', 'dob', 'enough', 'Natalie', 'chatting.', 'cost£3.75max', '42049', '-', 'FROM', '08706091795', '85233', 'CHIT-CHAT', 'outgoing.', 'WK.', 'cum.', 'W14RG', '08718723815.', 'Offer', '10k', 'Box334', '1x150p/wk.', 'WRC', 'tomorrow.', 'discreet', '09061209465', 'D=', 'over!', '150p/Mtmsgrcvd18', 'ads', "George's", 'BBC', 'clip', 'Account', 'TS&Cs', 'information.', '£800', 'easy,', 'meet.', 'Nasdaq', 'fgkslpo', 'account', '£400', '0870753331018+', 'dialling', 'M.', 'week,', 'margin', '89555.', '2wks', 'then', 'RP176781.', '£500', 'followed', 'celeb!4', 'today?', 'ladies', '#ERROR!', '82468', 'peak!', 'player', 'access', 'VIP', 'Rally', 'Germany', '45239', 'REPLY', 'know!', '08712402779', '08450542832', '09061701444.', 'knickers', '08706091795.', 'Ringtones', 'XXXMobileMovieClub:', 'charge.', '6HL', '09066362206', 'they', '09050001295', 'experiencehttp://www.vouch4me.com/etlp/dining.asp', 'To', 'busty', 'Next', 'mates', 'TITLE', 'is', 'STOP', 'polypH', 'Europe', 'Accident', "You've", 'order,', '09077818151', 'Dave', 'BT', 'Motorola,', 'GO!', 'great!', 'tips', 'CHARITY', 'Had', '08718738002', 'follow', 'wkly', 'Feb', 'Identifier', 'GET', 'These', 'men', '09064011000.', '09061701851.', '800', 'http://tms.', 'Txts', 'Close', 'landline,', 'dates', 'gr8', '07742676969', 'now!T&Cs', 'PoBox12n146tf150p', 'over?', 'now!Send', 'child', '!This', 'logo', 'YES-910', 'LA3', 'Camera!', 'redeemable', 'word:COLLECT', 'King', 'see!', 'calls.', 'TextOperator', 'entitled', 'box334sk38ch', 'This', 'T&Cs', 'scallies,', 'lnly', 'tone.', 'UR', 'GHOST,', 'perfect', 'Tomorrow?', 'MSG:We', '*', 'BANNEDUK', 'Free', 'Ave', 'Club4', 'StewartSize:', 'artists.', 'Golf', 'hit', 'play?', 'comp', 'them.', 'Male', 'BCMSFWC1N3XX', 'shot', 'Bears', 'Jersey', 'reward', 'free,', 'call', '08709501522', '08718726970', 'sort', '16+only!', 'SIM', 'old', 'of£2000', 'Important', 'James', 'Suite', 'Out', 'know', 'locations', 'choose', 'better?', 'GBP4.50/week.', 'NOW!REPLY', 'p£3.99', 'VILLA', 'informed', 'wml?id=1b6a5ecef91ff9*37819&first=true18:0430-JUL-05', 'customersqueries@netvision.uk.com', 'Toxic', 'Everyone', 'n', '8pm,', 'cst', 'http://alto18.co.uk/wave/wave.asp?o=44345', '09065069120', '£10,000', 'app', 'NO-165', '(18+).', '9am-11pm', 'luxury', 'mustprovide', 'laid?want', 'of', '07753741225', '08715203649', 'MQUIZ', 'mins', 'Adult', '69669.', '8714714', 'landlines!', 'B4', 'along', 'M', 'END', 'Messaging', 'Nokia,', 'Children', 'heart.', '10p.', '09065174042.', 'Manchester.', 'Police', 'ONCALL.', '4.', 'Lux', 'Videos', 'match', 'wk', 'min', 'concert', '087187262701.50gb

In [12]:
spamWordCount={}
for i in spamOnly.Message:
    # print(i)
    # print("\n")
    singleLine = i.split(' ')
    for j in singleLine:
        if j in spamWordCount:
            spamWordCount[j]=spamWordCount[j]+1
        else:
            spamWordCount[j]=1
    
print(spamWordCount)

# spamWordCount = spamOnly["Message"].str.split().explode().value_counts()

{'Free': 29, 'entry': 20, 'in': 53, '2': 150, 'a': 308, 'wkly': 7, 'comp': 7, 'to': 510, 'win': 19, 'FA': 2, 'Cup': 2, 'final': 9, 'tkts': 2, '21st': 1, 'May': 1, '2005.': 2, 'Text': 30, '87121': 2, 'receive': 24, 'question(std': 1, 'txt': 53, "rate)T&C's": 1, 'apply': 9, "08452810075over18's": 1, 'FreeMsg': 5, 'Hey': 5, 'there': 9, 'darling': 2, "it's": 2, 'been': 37, '3': 16, "week's": 2, 'now': 56, 'and': 102, 'no': 15, 'word': 11, 'back!': 1, "I'd": 2, 'like': 12, 'some': 6, 'fun': 6, 'you': 145, 'up': 17, 'for': 150, 'it': 19, 'still?': 1, 'Tb': 1, 'ok!': 1, 'XxX': 2, 'std': 2, 'chgs': 1, 'send,': 1, '£1.50': 12, 'rcv': 2, 'WINNER!!': 1, 'As': 9, 'valued': 7, 'network': 19, 'customer': 23, 'have': 107, 'selected': 21, 'receivea': 1, '£900': 6, 'prize': 37, 'reward!': 2, 'To': 63, 'claim': 62, 'call': 157, '09061701461.': 1, 'Claim': 23, 'code': 10, 'KL341.': 1, 'Valid': 17, '12': 3, 'hours': 4, 'only.': 5, 'Had': 11, 'your': 167, 'mobile': 68, '11': 3, 'months': 1, 'or': 154, 'more?': 1, 'U': 58, 'R': 6, 'entitled': 5, 'Update': 8, 'the': 157, 'latest': 19, 'colour': 10, 'mobiles': 5, 'with': 85, 'camera': 12, 'Free!': 3, 'Call': 114, 'The': 16, 'Mobile': 23, 'Co': 2, 'FREE': 73, 'on': 112, '08002986030': 1, 'SIX': 1, 'chances': 1, 'CASH!': 1, 'From': 5, '100': 13, '20,000': 1, 'pounds': 14, 'txt>': 1, 'CSH11': 1, 'send': 40, '87575.': 2, 'Cost': 12, '150p/day,': 1, '6days,': 1, '16+': 15, 'TsandCs': 1, 'Reply': 38, 'HL': 3, '4': 74, 'info': 5, 'URGENT!': 28, 'You': 65, 'won': 35, '1': 24, 'week': 24, 'membership': 1, 'our': 64, '£100,000': 1, 'Prize': 13, 'Jackpot!': 1, 'Txt': 54, 'word:': 8, 'CLAIM': 2, 'No:': 16, '81010': 1, 'T&C': 10, 'www.dbuk.net': 1, 'LCCLTD': 1, 'POBOX': 4, '4403LDNW1A7RW18': 1, 'XXXMobileMovieClub:': 1, 'use': 6, 'credit,': 1, 'click': 3, 'WAP': 5, 'link': 6, 'next': 14, 'message': 19, 'here>>': 1, 'http://wap.': 1, 'xxxmobilemovieclub.com?n=QJKGIGHJJGCBL': 1, 'England': 4, 'v': 2, 'Macedonia': 1, '-': 48, 'dont': 5, 'miss': 4, 'goals/team': 1, 'news.': 1, 'ur': 86, 'national': 6, 'team': 1, '87077': 7, 'eg': 10, 'ENGLAND': 2, 'Try:WALES,': 1, 'SCOTLAND': 1, '4txt/ú1.20': 1, 'POBOXox36504W45WQ': 1, 'Thanks': 13, 'subscription': 3, 'Ringtone': 4, 'UK': 7, 'will': 35, 'be': 41, 'charged': 11, '£5/month': 1, 'Please': 28, 'confirm': 1, 'by': 33, 'replying': 5, 'YES': 9, 'NO.': 1, 'If': 12, 'reply': 54, 'NO': 2, 'not': 20, '07732584351': 1, 'Rodger': 1, 'Burns': 1, 'MSG': 2, '=': 5, 'We': 31, 'tried': 16, 're': 9, 'sms': 3, 'free': 52, 'nokia': 4, '+': 15, 'camcorder.': 1, '08000930705': 14, 'delivery': 14, 'tomorrow': 6, 'SMS.': 4, 'ac': 4, 'Sptv:': 1, 'New': 15, 'Jersey': 1, 'Devils': 1, 'Detroit': 1, 'Red': 1, 'Wings': 1, 'play': 7, 'Ice': 1, 'Hockey.': 1, 'Correct': 1, 'Incorrect?': 1, 'End?': 2, 'END': 3, 'SPTV': 1, 'Congrats!': 4, 'year': 2, 'special': 2, 'cinema': 1, 'pass': 2, 'is': 125, 'yours.': 4, '09061209465': 1, 'now!': 37, 'C': 12, 'Suprman': 1, 'V,': 1, 'Matrix3,': 1, 'StarWars3,': 1, 'etc': 2, 'all': 21, 'FREE!': 10, 'bx420-ip4-5we.': 1, '150pm.': 1, 'Dont': 2, 'out!': 2, 'customer,': 4, 'I': 26, 'am': 9, 'pleased': 2, 'advise': 2, 'that': 19, 'following': 4, 'recent': 2, 'review': 3, 'of': 78, 'Mob': 2, 'No.': 5, 'are': 65, 'awarded': 30, '£1500': 2, 'Bonus': 13, 'Prize,': 3, '09066364589': 1, 'Urgent': 5, 'UR': 18, 'complimentary': 10, 'trip': 3, 'EuroDisinc': 1, 'Trav,': 1, 'Aco&Entry41': 1, 'Or': 2, '£1000.': 1, 'DIS': 1, '18+6*£1.50(moreFrmMob.': 1, 'ShrAcomOrSglSuplt)10,': 1, 'LS1': 1, '3AJ': 1, 'Did': 1, 'hear': 3, 'about': 7, 'new': 39, '"Divorce': 1, 'Barbie"?': 1, 'It': 2, 'comes': 3, "Ken's": 1, 'stuff!': 1, 'service': 37, 'representative': 6, '0800': 9, '169': 1, '6031': 1, 'between': 6, '10am-9pm': 1, 'as': 17, 'WON': 14, 'guaranteed': 19, '£1000': 26, 'cash': 36, '£5000': 12, 'prize!': 9, 'Your': 64, 'ringtone': 13, 'waiting': 14, 'collected.': 1, 'Simply': 1, 'text': 61, 'password': 2, '"MIX"': 1, '85069': 1, 'verify.': 1, 'Get': 25, 'Usher': 1, 'Britney.': 1, 'FML,': 1, 'PO': 24, 'Box': 18, '5249,': 1, 'MK17': 1, '92H.': 1, '450Ppw': 1, '16': 19, 'GENT!': 1, 'trying': 13, 'contact': 48, 'you.': 7, 'Last': 7, 'weekends': 4, 'draw': 27, 'shows': 28, 'GUARANTEED.': 16, '09064012160.': 1, 'Code': 3, 'K52.': 1, '12hrs': 15, '150ppm': 21, 'winner': 9, 'specially': 8, '4*': 19, 'holiday': 8, '(flights': 3, 'inc)': 3, 'speak': 4, 'live': 14, 'operator': 10, '0871277810910p/min': 1, '(18+)': 3, 'PRIVATE!': 15, '2004': 4, 'Account': 15, 'Statement': 15, '07742676969': 1, '786': 3, 'unredeemed': 3, 'Points.': 2, '08719180248': 1, 'Identifier': 15, 'Code:': 12, '45239': 2, 'Expires': 16, 'was': 9, '£2000': 18, 'Caller': 10, '5/9/03': 1, 'This': 34, 'try': 3, 'U!': 2, 'from': 107, 'Landline': 5, '09064019788': 1, 'BOX42WR29C,': 1, '150PPM': 2, 'Todays': 14, 'Voda': 5, 'numbers': 8, 'ending': 7, '7548': 1, '$350': 1, 'award.': 9, 'match': 5, 'please': 18, '08712300220': 6, 'quoting': 5, '4041': 1, 'standard': 6, 'rates': 8, 'app': 4, 'Sunshine': 4, 'Quiz': 4, 'Wkly': 2, 'Q!': 2, 'Win': 11, 'top': 10, 'Sony': 3, 'DVD': 4, 'player': 8, 'if': 13, 'u': 37, 'know': 15, 'which': 5, 'country': 2, 'Algarve': 1, 'in?': 1, 'ansr': 2, '82277.': 3, 'SP:Tyrone': 2, 'Want': 11, 'get': 38, 'laid': 3, 'tonight?': 2, 'real': 9, 'Dogging': 9, 'locations': 5, 'sent': 9, 'direct': 8, 'mob?': 1, 'Join': 6, "UK's": 5, 'largest': 4, 'Network': 2, 'bt': 1, 'Txting': 1, 'GRAVEL': 1, '69888!': 1, 'Nt.': 1, 'ec2a.': 4, '31p.msg@150p': 2, "You'll": 1, 'any': 22, 'more': 16, 'msgs': 2, 'chat': 14, 'svc.': 1, 'For': 22, 'Hardcore': 1, 'services': 11, 'GO': 8, 'to:': 1, '69988': 1, 'nothing': 2, 'must': 2, 'Age': 1, 'Verify': 1, 'yr': 11, '&': 88, 'again': 1, 'Why': 4, "haven't": 1, 'replied': 1, 'my': 9, 'text?': 1, "I'm": 8, 'Randy,': 1, 'sexy,': 1, 'female': 1, 'local.': 1, 'Luv': 5, 'u.': 6, 'Netcollex': 4, 'Ltd': 4, '08700621170150p': 2, 'per': 38, 'msg': 13, 'Stop': 7, 'end': 7, 'Customer': 9, 'annoncement.': 1, 'Years': 2, '07046744435': 1, 'arrange': 2, '0871277810810': 1, '-PLS': 1, 'STOP': 40, 'bootydelious': 1, '(32/F)': 1, 'inviting': 5, 'her': 6, 'friend.': 5, 'YES-434': 1, 'NO-434': 1, 'See': 8, 'her:': 4, 'www.SMS.ac/u/bootydelious': 1, 'STOP?': 5, 'Send': 15, 'FRND': 5, '62468': 6, 'BangBabes': 1, 'Ur': 15, 'order': 6, 'way.': 1, 'SHOULD': 1, 'Service': 5, 'Msg': 2, 'download': 2, 'content.': 5, 'do': 10, 'not,': 1, 'GoTo': 1, 'wap.': 3, 'bangb.': 1, 'tv': 1, 'internet/service': 1, 'menu': 1, '09061701939.': 1, 'S89.': 1, 'only': 37, 'FREEPHONE': 4, '0808': 1, '145': 1, '4742': 1, '9am-11pm': 1, 'Are': 1, 'unique': 2, 'enough?': 1, 'Find': 3, 'out': 36, '30th': 1, 'August.': 1, 'www.areyouunique.co.uk': 1, '500': 19, 'Mobiles': 3, '2004,': 3, 'MUST': 3, 'GO!': 3, 'Txt:': 6, 'NOKIA': 12, '89545': 3, 'collect': 14, 'yours': 5, 'today!From': 2, 'ONLY': 6, '£1': 2, 'www.4-tc.biz': 3, '2optout': 4, '087187262701.50gbp/mtmsg18': 3, 'Will': 3, 'meet': 4, 'dream': 1, 'partner': 4, 'soon?': 1, 'Is': 1, 'career': 1, 'off': 2, 'flyng': 1, 'start?': 1, 'find': 16, 'free,': 2, 'HORO': 2, 'followed': 3, 'star': 1, 'sign,': 1, 'e.': 2, 'g.': 2, 'ARIES': 1, 'someone': 7, 'sexy': 10, 'today.': 2, 'can': 21, 'date': 3, 'even': 6, 'flirt': 2, 'its': 4, 'U.': 10, 'just': 42, '10p.': 1, 'REPLY': 1, 'NAME': 4, 'AGE': 6, 'Sam': 1, '25.': 1, '18': 17, '-msg': 1, 'recd@thirtyeight': 1, 'pence': 3, '447801259231': 1, 'secret': 5, 'admirer': 4, 'who': 36, 'looking': 7, 'make': 9, 'U-find': 6, 'they': 12, 'R*reveal': 6, 'thinks': 7, 'so': 16, 'special-call': 6, '09058094597': 1, 'Congratulations': 9, 'CD': 7, 'vouchers': 10, '125gift': 2, 'MUSIC': 8, '87066': 10, 'TnCs': 5, 'www.Ldew.com1win150ppmx3age16': 2, 'offer': 7, 'Video': 10, 'Handset?': 2, '750': 17, 'anytime': 12, 'networks': 2, 'mins?': 6, 'UNLIMITED': 6, 'TEXT?': 3, 'Camcorder?': 4, 'NOW': 18, 'really': 1, 'horny': 6, 'want': 16, 'see': 7, 'me': 19, 'naked': 1, 'hot': 7, '69698': 2, 'at': 24, '150pm': 2, 'unsubscribe': 12, 'stop': 37, 'has': 27, 'changed!': 1, '25': 2, 'credits!': 1, 'Go': 3, 'club4mobiles.com': 1, 'choose': 3, 'content': 5, 'Stop?': 2, 'CLUB': 2, '87070.': 1, '150p/wk': 1, 'Club4': 1, 'Box1146': 1, 'MK45': 2, '2WT': 2, 'Club:': 4, 'singles': 3, 'chart': 1, 'each': 6, 'quality': 2, 'ringtone!': 1, 'charge.': 5, 'HMV': 4, 'BONUS': 1, 'SPECIAL': 1, 'genuine': 1, 'won.': 1, 'Just': 22, 'answer': 5, 'easy': 1, 'questions.': 1, 'Play': 3, 'Now!': 4, '86688': 13, 'More': 4, 'info:www.100percent-real.com': 1, 'T-Mobile': 2, 'may': 5, 'CAMERA': 3, 'PHONE': 3, 'upgrade': 3, 'pay': 1, 'go': 14, 'sim': 1, 'card': 1, 'loyalty.': 3, '0845': 3, '021': 2, '3680.Offer': 1, 'ends': 4, "28thFeb.T&C's": 1, 'Blind': 2, 'Date': 1, '4U!:': 1, 'Rodds1': 1, '21/m': 1, 'Aberdeen,': 1, 'United': 1, 'Kingdom.': 1, 'Check': 4, 'Him': 1, 'http://img.': 1, 'sms.': 3, 'ac/W/icmb3cktz8r7!-4': 1, 'Dates': 1, 'HIDE': 1, 'TheMob>': 1, 'newest': 3, 'selection': 4, 'content,': 1, 'Games,': 1, 'Tones,': 1, 'Gossip,': 1, 'babes': 2, 'sport,': 2, 'Keep': 1, 'fit': 1, 'funky': 1, '82468': 2, 'Think': 2, 'smart': 1, '?': 5, '£200': 9, 'this': 41, 'weekly': 17, 'quiz,': 1, 'PLAY': 2, '85222': 1, 'now!T&Cs': 1, 'WinnersClub': 1, 'BOX': 8, '84,': 1, 'M26': 3, '3UZ.': 1, '16+.': 3, 'GBP1.50/week': 1, 'December': 3, 'only!': 4, '11mths+?': 3, 'update': 4, '08002986906': 2, 'Germany': 3, 'minute!': 2, 'fixed': 2, 'line': 14, 'via': 3, 'access': 5, 'number': 25, '0844': 2, '861': 2, '85': 2, '85.': 2, 'No': 12, 'prepayment.': 2, 'Direct': 2, 'access!': 2, 'Valentines': 2, 'Day': 3, 'Special!': 2, 'over': 4, 'quiz': 2, 'take': 10, 'lifetime!': 2, '83600': 3, 'now.': 14, '150p/msg': 4, 'rcvd.': 3, 'CustCare:08718720201.': 1, 'Fancy': 5, 'shag?': 1, 'do.Interested?': 1, 'sextextuk.com': 1, 'XXUK': 1, 'SUZY': 1, '69876.': 1, 'Txts': 1, 'cost': 6, '1.50': 2, 'msg.': 4, 'website.': 1, 'X': 4, 'cash-balance': 7, 'currently': 9, 'maximize': 7, 'cash-in': 7, 'CASH': 8, '150p/msg.': 5, 'CC:': 5, '08708800282': 1, 'HG/Suite342/2Lands': 5, 'Row/W1J6HL': 3, 'Update_Now': 2, 'Xmas': 8, 'Offer!': 4, 'Latest': 9, 'Motorola,': 6, 'SonyEricsson': 5, 'Nokia': 34, 'Bluetooth!': 1, 'Double': 10, 'Mins': 7, '1000': 4, 'Orange.': 4, 'MobileUpd8': 12, '08000839402': 12, 'call2optout/F4Q=': 1, 'Here': 1, 'discount': 6, 'RP176781.': 1, 'further': 3, 'messages': 6, 'stop.': 3, 'www.regalportfolio.co.uk.': 1, 'Services': 1, '08717205546': 1, 'Order,': 1, 'Reference': 1, 'T91.': 1, 'GBP': 1, 'week.': 3, 'calling': 4, '09057039994': 1, 'mins': 14, 'txts': 7, '6months': 1, 'Bluetooth': 6, 'Available': 1, 'Sony,': 1, 'Motorola': 4, 'phones.': 1, 'call2optout/N9DX': 1, '4mths': 2, 'half': 4, 'price': 8, 'Orange': 15, 'rental': 5, 'phones': 8, 'FREE.': 7, 'phone': 25, '11mths': 3, 'MobilesDirect': 2, '08000938767': 2, 'or2stoptxt': 2, 'RINGTONE': 3, 'FIRST': 1, '87131': 3, 'poly': 4, 'GET': 4, 'true': 1, 'tone!': 1, 'Help?': 3, '2814032': 1, 'after': 4, '1st': 19, 'tones': 16, '3x£150pw': 1, 'e£nd': 1, 'dating': 13, 'cal;l': 1, '09064012103': 1, 'box334sk38ch': 1, 'into': 6, '£250': 13, 'competition': 1, 'WIN': 14, '80086': 2, 'NOW.': 6, 'www.txttowin.co.uk': 2, 'logo': 3, 'lover': 2, 'names': 2, 'joined': 2, 'heart.': 2, 'LOVE': 4, 'NAME1': 2, 'NAME2': 2, 'MOBNO': 2, 'ADAM': 2, 'EVE': 2, '07123456789': 2, 'Yahoo!': 2, 'POBox36504W45WQ': 4, 'TxtNO': 2, 'ads': 2, '150p': 17, 'Someone': 6, 'contacted': 5, 'entered': 6, 'because': 2, 'fancy': 4, 'you!': 11, 'landline': 6, '09111032124': 1, '.': 10, 'PoBox12n146tf150p': 1, '09058094455': 1, 'land': 16, 'line.': 15, '3030.': 6, '3650': 1, 'video': 16, '09066382422': 1, 'Calls': 4, 'Ave': 1, '3mins': 3, 'vary': 3, 'Close': 1, '300603': 1, 'post': 1, 'BCM4284': 1, 'Ldn': 1, 'WC1N3XX': 2, 'Loan': 1, 'purpose': 2, '£500': 14, '£75,000.': 1, 'Homeowners': 1, 'Tenants': 2, 'welcome.': 1, 'Have': 3, 'previously': 1, 'refused?': 1, 'still': 4, 'help.': 1, '1956669': 1, 'back': 15, "'help'": 2, 'UpgrdCentre': 1, '0207': 2, '153': 2, '9153.': 1, 'Offer': 5, '26th': 1, 'July.': 1, "T&C's": 5, 'apply.': 13, 'Opt-out': 3, 'available': 1, 'okmail:': 1, 'Dear': 15, 'Dave': 2, 'notice': 3, 'Tenerife': 7, 'Holiday': 17, '#5000': 3, 'award!': 4, '09061743806': 2, 'landline.': 13, 'TCs': 2, 'SAE': 14, 'Box326': 2, 'CW25WX': 4, 'Mob?': 1, 'txting': 6, 'MOAN': 1, '69888Nyt.': 1, 'MESSAGE': 1, 'Activate': 2, 'Messages': 1, 'terms': 2, 'conditions,': 1, 'visit': 5, 'www.07781482378.com': 1, '#ERROR!': 1, 'Phone,': 4, '40GB': 6, 'iPod': 6, 'MP3': 5, 'COLLECT': 4, '83355!': 3, 'IBHltd': 3, 'LdnW15H': 3, '150p/Mtmsgrcvd18+': 1, 'Boltblue': 1, 'POLY#': 1, 'MONO#': 1, 'POLY3': 1, '1.': 2, 'Cha': 2, 'Slide': 1, '2.': 2, 'Yeah': 1, '3.': 3, 'Slow': 1, 'Jamz': 1, '6.': 1, 'Toxic': 1, '8.': 1, 'Come': 1, 'With': 6, 'Me': 1, 'MORE': 1, 'credits': 4, 'topped': 1, 'http://www.bubbletext.com': 1, 'renewal': 1, 'Pin': 1, 'tgxxrz': 1, 'URGENT!:': 1, '£2,000': 11, '02/09/03!': 2, '2nd': 18, 'attempt': 19, 'YOU!': 11, '0871-872-9755': 1, 'BOX95QU': 3, "Today's": 2, '£150': 5, 'worth': 7, 'vouchers!': 1, '85023': 4, 'SavaMob,': 4, 'member': 3, 'offers': 8, 'mobile!': 6, 'T': 7, 'Cs': 5, '08717898035.': 2, '£3.00': 4, 'Sub.': 3, 'Unsub': 2, 'recieve': 1, 'tone': 14, 'within': 4, '24hrs.': 1, 'Terms': 3, 'conditions': 2, 'Channel': 1, 'Teletext': 1, 'Pg': 1, '2003': 13, '07815296484': 1, '800': 13, 'un-redeemed': 12, 'S.I.M.': 3, 'points.': 13, '08718738001': 2, '41782': 1, '18/11/04': 1, 'www.Applausestore.com': 1, 'MonthlySubscription@50p/msg': 1, 'max6/month': 1, 'T&CsC': 1, 'web': 2, 'age16': 3, '2stop': 1, '?1,000': 2, '?2,000': 2, 'claim,': 3, 'call09050000327': 1, '£5000,': 1, 'calls': 3, 'us': 4, 'ring': 1, 'claims': 2, '09050005321.': 1, '150': 7, 'textand': 1, '08002988890': 1, 'chance': 15, 'shopping': 3, 'spree': 5, 'TXT:': 4, 'SHOP': 2, '80878.': 1, "T's&C's": 4, 'www.txt-2-shop.com': 1, 'custcare': 6, '08715705022,': 2, '1x150p/wk': 2, '2000': 1, 'pound': 2, '08712402050': 2, 'BEFORE': 2, 'lines': 2, 'close.': 2, '10ppm.': 2, 'T&Cs': 17, 'AG': 2, 'Promo': 2, '07753741225': 1, 'S.': 9, 'I.': 9, 'M.': 9, '08715203677': 1, '42478': 1, '24/10/04': 1, 'an': 18, 'important': 6, 'announcement.': 3, '542': 3, '0825': 1, 'XCLUSIVE@CLUBSAISAI': 1, '2MOROW': 1, '28/5': 1, 'SOIREE': 1, 'SPECIALE': 1, 'ZOUK': 1, 'WITH': 1, 'NICHOLS': 1, 'FROM': 4, 'PARIS.FREE': 1, 'ROSES': 1, 'ALL': 2, 'LADIES': 1, '!!!': 1, 'info:': 1, '07946746291/07880867867': 1, '22': 1, 'days': 5, 'kick': 2, 'off!': 2, 'Euro2004': 2, 'kept': 2, 'news': 5, 'results': 2, 'daily.': 3, 'removed': 1, 'TXT': 5, '83222': 1, 'TEXTBUDDY': 2, 'Chat': 7, 'guys': 3, 'area': 5, '25p': 6, 'Search': 2, 'postcode': 3, 'gaytextbuddy.com.': 2, 'ONE': 3, 'name': 7, '89693': 1, 'Vodafone': 2, '4882': 1, '£350': 8, 'matches': 5, '09064019014': 1, 'Voucher': 6, 'Holder,': 4, 'weeks': 8, 'offer,': 4, 'PC': 4, 'http://www.e-tlp.co.uk/expressoffer': 2, 'Ts&Cs': 8, 'apply.2': 1, 'texts': 15, '80062.': 1, '08715203694': 1, '40533': 2, '31/10/04': 2, 'call09050000327.': 1, 'T&C:': 2, 'RSTM,': 2, 'SW7': 2, '3SS.': 2, '88800': 1, '89034': 1, 'premium': 2, '08718711108': 1, 'sun0819': 1, 'posts': 1, 'HELLO:"You': 1, 'seem': 1, 'cool,': 1, 'wanted': 1, 'say': 1, 'hi.': 1, 'HI!!!"': 1, 'NOW!': 12, 'TONE.': 1, 'Gr8': 5, 'TOP': 1, '20': 3, 'every': 25, 'wk': 8, 'opt': 8, '08452810071': 1, 'Hi': 10, 'sue.': 1, 'years': 2, 'old': 2, 'work': 3, 'lapdancer.': 1, 'love': 6, 'sex.': 1, 'i': 6, 'bedroom': 1, 'SUE': 1, '89555.': 1, 'By': 1, 'TextOperator': 1, 'G2': 1, '1DA': 1, '150ppmsg': 1, '18+': 12, '<Forwarded': 4, '448712404000>Please': 1, 'CALL': 18, '08712404000': 1, 'immediately': 5, 'urgent': 5, 'KEEP': 2, 'fantastic': 3, 'N-Gage': 1, 'game': 3, 'deck': 1, 'Club': 3, 'Nokia,': 1, 'www.cnupdates.com/newsletter.': 1, 'alerts': 1, 'OUT': 5, '08714712388': 1, '10am-7pm': 4, '10p': 12, 'prize.': 14, '08714712394': 1, 'Email': 1, 'AlertFrom:': 1, 'Jeri': 1, 'StewartSize:': 1, '2KBSubject:': 1, 'Low-cost': 1, 'prescripiton': 1, 'drvgsTo': 1, 'listen': 1, 'email': 1, '123': 1, 'Hi.': 1, 'Loyalty': 3, 'Offer:The': 2, 'NEW': 10, 'Nokia6650': 2, '£10': 3, 'TXTAUCTION!': 2, 'START': 2, '81151': 2, '4T&Ctxt': 2, 'TC': 4, '150p/MTmsg': 2, 'subscribed': 3, 'best': 4, 'Content': 3, '£3': 4, '10': 6, 'until': 5, '82324.': 1, 'Helpline': 2, '08706091795': 1, 'Do': 13, 'realize': 1, '40': 2, 'years,': 1, "we'll": 2, 'thousands': 1, 'ladies': 1, 'running': 1, 'around': 2, 'tattoos?': 1, 'announcement': 2, 'PREMIER.': 2, 'Romantic': 1, 'Paris.': 1, 'nights,': 1, 'flights': 2, '£79': 1, 'Book': 1, 'year.': 1, '08704439680Ts&Cs': 1, 'award': 10, 'unclaimed!': 1, '09066368327': 1, 'closingdate04/09/02': 1, 'claimcode': 1, 'M39M51': 1, '£1.50pmmorefrommobile2Bremoved-MobyPOBox734LS27YF': 1, 'City': 3, 'Break': 4, 'could': 7, 'Summer': 3, 'Shopping': 4, 'WK.': 3, 'STORE': 4, '88039': 2, 'SkilGme.': 3, 'TsCs087147403231Winawk!Age16': 2, '£1.50perWKsub': 2, '0578': 2, 'Ever': 1, 'thought': 1, 'living': 1, 'good': 4, 'life': 2, 'perfect': 1, 'partner?': 1, 'join': 9, 'community.': 1, '(100p/SMS)': 1, '5': 6, 'Top': 2, 'Polyphonic': 1, 'Tones': 6, '087018728737,': 1, 'National': 5, 'Rate.': 1, 'toppoly': 1, 'tune': 1, 'week,': 1, 'SUBPOLY': 2, '81618,': 1, 'pole.': 1, 'UnSub': 1, '08718727870.': 1, '9996.': 1, '14thMarch.': 1, 'availa': 1, 'Chance!': 2, 'today!': 5, 'SavaMob': 4, 'POBOX84,': 2, 'M263UZ.': 2, 'week!': 7, 'No1': 5, '8077': 1, 'tell': 8, 'mates.': 2, 'www.getzed.co.uk': 5, 'POBox': 7, '36504': 4, 'W45WQ': 3, 'norm150p/tone': 3, 'cashto': 2, '08000407165': 2, 'getstop': 2, '88222': 2, 'PHP.': 1, 'RG21': 1, '4JX': 1, 'either': 8, 'gift': 12, '£100': 18, 'were': 4, 'outbid': 1, 'simonwatson5120': 1, 'Shinco': 1, 'Plyr.': 1, 'bid': 6, 'again,': 1, 'ac/smsrewards': 1, 'notifications,': 1, 'SMSSERVICES.': 1, 'yourinclusive': 1, 'credits,': 3, 'pls': 6, 'goto': 3, 'www.comuk.net': 4, 'login=': 3, '3qxj9': 3, 'STOP,': 2, 'extra': 5, 'help': 3, '08702840625.COMUK.': 2, '220-CM2': 2, '9AE': 3, 'alfie': 2, "Moon's": 3, 'Children': 3, 'need': 6, 'song': 3, 'mob.': 3, 'Tell': 3, 'm8s.': 3, 'Tone': 6, 'charity': 5, '8007': 16, 'Nokias': 2, 'Poly': 3, 'polys:': 2, 'zed': 4, '08701417012': 3, 'profit': 3, 'charity.': 2, 'admirer.': 1, 'REVEAL': 2, 'So': 1, 'special.': 1, '09065174042.': 1, 'STOP.': 7, 'recd.': 1, 'Cust': 1, 'care': 3, '07821230901': 1, 'texts,': 1, '80062': 4, 'VIDEO': 1, 'five': 3, '08002888812': 2, 'Phone': 4, 'HALF': 1, 'PRICE': 1, 'Rental': 2, 'camcorder': 6, 'Wed': 1, 'vouchers-Text': 1, 'now!SavaMob-member': 1, 'Remove': 2, 'Urgent!': 10, '09066350750': 1, 'Ibiza': 3, '10,000': 1, 'await': 15, 'collection': 9, '434': 2, 'SK3': 2, '8WP': 2, 'ppm': 3, 'Talk': 1, 'sexy!!': 1, 'Make': 2, 'friends': 1, 'fall': 1, 'worlds': 1, 'most': 2, 'discreet': 2, 'service.': 4, 'VIP': 4, '83110': 1, 'meet.': 1, 'yrs': 3, 'supply': 2, 'CDs': 4, 'Virgin': 1, 'Records': 1, 'Mystery': 1, 'Gift': 3, 'GUARANTEED': 3, '09061104283': 1, 'www.smsco.net': 2, '£1.50pm': 1, 'approx': 1, '07808': 1, 'XXXXXX': 1, '08719899217': 1, '41685': 2, '07/11/04': 2, 'Hello.': 1, 'posh': 1, 'birds': 1, 'chaps': 1, 'user': 4, 'trial': 1, 'prods': 1, 'champneys.': 1, 'Can': 4, 'put': 1, 'down?': 1, 'address': 3, 'dob': 1, 'asap.': 1, 'Ta': 1, 'r': 12, 'What': 3, 'Xmas?': 1, 'How': 5, 'rental?': 2, '0721072': 1, 'more!': 1, 'Shop': 1, 'till': 2, 'Drop,': 1, 'IS': 6, 'IT': 1, 'YOU,': 1, '10K,': 1, '5K,': 1, 'Cash': 2, 'Travel': 1, 'voucher,': 1, 'now,': 1, '09064011000.': 1, 'NTT': 7, 'CR01327BT': 1, 'fixedline': 1, 'Liverpool': 2, 'played': 1, 'mid': 1, 'week?': 1, '09058094565': 2, 'Secret': 2, 'Admirer': 2, '09065171142-stopsms-08': 1, 'Reminder:': 1, 'downloaded': 1, 'already': 1, 'paid': 1, 'for.': 1, 'Goto': 1, 'http://doit.': 1, 'mymoby.': 1, 'tv/': 1, 'lastest': 1, 'Stereophonics,': 1, 'Marley,': 1, 'Dizzee': 1, 'Racal,': 1, 'Libertines': 1, 'Strokes!': 1, 'Nookii': 1, 'games': 4, 'Flirt!!': 1, 'Click': 2, 'TheMob': 1, 'Bookmark': 1, 'January': 1, 'Male': 2, 'Sale!': 2, 'Hot': 2, 'Gay': 2, 'cheaper,': 2, '08709222922.': 2, 'rate': 9, '1.5p/min': 2, 'cheap': 2, '7.8p/min': 2, 'peak!': 2, '08712460324': 7, '(10p/min)

In [13]:
sortedSpamWordCount = dict(sorted(spamWordCount.items(), key=lambda item: item[1],reverse=True))

In [14]:
print(sortedSpamWordCount)

{'to': 510, 'a': 308, 'your': 167, 'call': 157, 'the': 157, 'or': 154, '2': 150, 'for': 150, 'you': 145, 'is': 125, 'Call': 114, 'on': 112, 'have': 107, 'from': 107, 'and': 102, '&': 88, 'ur': 86, 'with': 85, 'of': 78, '4': 74, 'FREE': 73, 'mobile': 68, 'You': 65, 'are': 65, 'our': 64, 'Your': 64, 'To': 63, 'claim': 62, 'text': 61, 'U': 58, 'now': 56, 'Txt': 54, 'reply': 54, 'in': 53, 'txt': 53, 'free': 52, '-': 48, 'contact': 48, 'just': 42, 'be': 41, 'this': 41, 'send': 40, 'STOP': 40, 'new': 39, 'Reply': 38, 'get': 38, 'per': 38, 'been': 37, 'prize': 37, 'now!': 37, 'service': 37, 'u': 37, 'only': 37, 'stop': 37, 'cash': 36, 'out': 36, 'who': 36, 'won': 35, 'will': 35, 'This': 34, 'Nokia': 34, 'by': 33, 'We': 31, 'Text': 30, 'awarded': 30, 'Free': 29, 'URGENT!': 28, 'Please': 28, 'shows': 28, 'draw': 27, 'has': 27, 'I': 26, '£1000': 26, 'Get': 25, 'number': 25, 'phone': 25, 'every': 25, 'receive': 24, '1': 24, 'week': 24, 'PO': 24, 'at': 24, 'customer': 23, 'Claim': 23, 'Mobile': 23, 'any': 22, 'For': 22, 'Just': 22, 'selected': 21, 'all': 21, '150ppm': 21, 'can': 21, 'entry': 20, 'not': 20, 'win': 19, 'it': 19, 'network': 19, 'latest': 19, 'message': 19, 'that': 19, 'guaranteed': 19, '16': 19, '4*': 19, '500': 19, 'me': 19, '1st': 19, 'attempt': 19, 'UR': 18, 'Box': 18, '£2000': 18, 'please': 18, 'NOW': 18, '2nd': 18, 'an': 18, 'CALL': 18, '£100': 18, 'up': 17, 'Valid': 17, 'as': 17, '18': 17, '750': 17, 'weekly': 17, '150p': 17, 'Holiday': 17, 'T&Cs': 17, '3': 16, 'The': 16, 'No:': 16, 'tried': 16, 'GUARANTEED.': 16, 'Expires': 16, 'more': 16, 'find': 16, 'so': 16, 'want': 16, 'tones': 16, 'land': 16, 'video': 16, '8007': 16, 'no': 15, '16+': 15, '+': 15, 'New': 15, '12hrs': 15, 'PRIVATE!': 15, 'Account': 15, 'Statement': 15, 'Identifier': 15, 'know': 15, 'Send': 15, 'Ur': 15, 'Orange': 15, 'line.': 15, 'back': 15, 'Dear': 15, 'chance': 15, 'texts': 15, 'await': 15, 'time': 15, 'pounds': 14, 'next': 14, '08000930705': 14, 'delivery': 14, 'WON': 14, 'waiting': 14, 'live': 14, 'Todays': 14, 'chat': 14, 'collect': 14, 'go': 14, 'line': 14, 'now.': 14, 'mins': 14, 'WIN': 14, '£500': 14, 'SAE': 14, 'tone': 14, 'prize.': 14, '100': 13, 'Prize': 13, 'Thanks': 13, 'Bonus': 13, 'ringtone': 13, 'trying': 13, 'if': 13, 'msg': 13, '86688': 13, 'dating': 13, '£250': 13, 'apply.': 13, 'landline.': 13, '2003': 13, '800': 13, 'points.': 13, 'Do': 13, 'A': 13, 'like': 12, '£1.50': 12, 'camera': 12, 'Cost': 12, 'If': 12, 'C': 12, '£5000': 12, 'Code:': 12, 'NOKIA': 12, 'they': 12, 'anytime': 12, 'unsubscribe': 12, 'No': 12, 'MobileUpd8': 12, '08000839402': 12, 'un-redeemed': 12, 'NOW!': 12, '18+': 12, '10p': 12, 'gift': 12, 'r': 12, 'collection.': 12, 'word': 11, 'Had': 11, 'charged': 11, 'Win': 11, 'Want': 11, 'services': 11, 'yr': 11, 'you!': 11, '£2,000': 11, 'YOU!': 11, 'Only': 11, 'we': 11, 'code': 10, 'colour': 10, 'T&C': 10, 'eg': 10, 'FREE!': 10, 'complimentary': 10, 'operator': 10, 'Caller': 10, 'top': 10, 'do': 10, 'sexy': 10, 'U.': 10, 'vouchers': 10, '87066': 10, 'Video': 10, 'take': 10, 'Double': 10, '.': 10, 'Hi': 10, 'NEW': 10, 'award': 10, 'Urgent!': 10, 'CHAT': 10, 'SMS': 10, 'final': 9, 'apply': 9, 'there': 9, 'As': 9, 'YES': 9, 're': 9, 'am': 9, '0800': 9, 'prize!': 9, 'winner': 9, 'was': 9, 'award.': 9, 'real': 9, 'Dogging': 9, 'sent': 9, 'my': 9, 'Customer': 9, 'make': 9, 'Congratulations': 9, '£200': 9, 'currently': 9, 'Latest': 9, 'S.': 9, 'I.': 9, 'M.': 9, 'join': 9, 'collection': 9, 'rate': 9, 'Update': 8, 'word:': 8, 'specially': 8, 'holiday': 8, 'numbers': 8, 'rates': 8, 'player': 8, 'direct': 8, 'GO': 8, "I'm": 8, 'See': 8, 'MUSIC': 8, 'BOX': 8, 'CASH': 8, 'Xmas': 8, 'price': 8, 'phones': 8, 'offers': 8, '£350': 8, 'weeks': 8, 'Ts&Cs': 8, 'wk': 8, 'opt': 8, 'tell': 8, 'either': 8, 'mob': 8, 'Good': 8, 'what': 8, 'min': 8, 'FOR': 8, 'TONE': 8, 'wkly': 7, 'comp': 7, 'valued': 7, '87077': 7, 'UK': 7, 'play': 7, 'about': 7, 'you.': 7, 'Last': 7, 'ending': 7, 'Stop': 7, 'end': 7, 'someone': 7, 'looking': 7, 'thinks': 7, 'CD': 7, 'offer': 7, 'see': 7, 'hot': 7, 'cash-balance': 7, 'maximize': 7, 'cash-in': 7, 'Mins': 7, 'txts': 7, 'FREE.': 7, 'Tenerife': 7, 'worth': 7, 'T': 7, '150': 7, 'Chat': 7, 'name': 7, 'could': 7, 'week!': 7, 'POBox': 7, 'STOP.': 7, 'NTT': 7, '08712460324': 7, '£800': 7, 'voucher': 7, 'YOU': 7, 'n': 7, 'when': 7, 'easy,': 7, 'Half': 7, 'some': 6, 'fun': 6, '£900': 6, 'R': 6, 'use': 6, 'link': 6, 'national': 6, 'tomorrow': 6, 'representative': 6, 'between': 6, '08712300220': 6, 'standard': 6, 'Join': 6, 'u.': 6, 'her': 6, '62468': 6, 'order': 6, 'Txt:': 6, 'ONLY': 6, 'even': 6, 'AGE': 6, 'U-find': 6, 'R*reveal': 6, 'special-call': 6, 'mins?': 6, 'UNLIMITED': 6, 'horny': 6, 'each': 6, 'cost': 6, 'Motorola,': 6, 'discount': 6, 'messages': 6, 'Bluetooth': 6, 'into': 6, 'NOW.': 6, 'Someone': 6, 'entered': 6, 'landline': 6, '3030.': 6, 'txting': 6, '40GB': 6, 'iPod': 6, 'With': 6, 'mobile!': 6, 'custcare': 6, 'important': 6, '25p': 6, 'Voucher': 6, 'love': 6, 'i': 6, '10': 6, '5': 6, 'Tones': 6, 'bid': 6, 'pls': 6, 'need': 6, 'Tone': 6, 'camcorder': 6, 'IS': 6, 'lucky': 6, '!': 6, 'give': 6, 'Wanna': 6, 'enter': 6, 'then': 6, 'pics': 6, 'Ltd,': 6, 'but': 6, 'Our': 6, 'arrive': 6, 'ON': 6, 'details': 6, 'being': 6, 'FreeMsg': 5, 'Hey': 5, 'only.': 5, 'entitled': 5, 'mobiles': 5, 'From': 5, 'info': 5, 'WAP': 5, 'dont': 5, 'replying': 5, '=': 5, 'No.': 5, 'Urgent': 5, 'Landline': 5, 'Voda': 5, 'match': 5, 'quoting': 5, 'which': 5, 'locations': 5, "UK's": 5, 'Luv': 5, 'inviting': 5, 'friend.': 5, 'STOP?': 5, 'FRND': 5, 'Service': 5, 'content.': 5, 'yours': 5, 'secret': 5, 'TnCs': 5, 'content': 5, 'charge.': 5, 'answer': 5, 'may': 5, '?': 5, 'access': 5, 'Fancy': 5, '150p/msg.': 5, 'CC:': 5, 'HG/Suite342/2Lands': 5, 'SonyEricsson': 5, 'rental': 5, 'contacted': 5, 'Offer': 5, "T&C's": 5, 'visit': 5, 'MP3': 5, '£150': 5, 'Cs': 5, 'spree': 5, 'days': 5, 'news': 5, 'TXT': 5, 'area': 5, 'matches': 5, 'Gr8': 5, 'immediately': 5, 'urgent': 5, 'OUT': 5, 'until': 5, 'National': 5, 'today!': 5, 'No1': 5, 'www.getzed.co.uk': 5, 'extra': 5, 'charity': 5, 'How': 5, '£10,000': 5, 'Enjoy': 5, '08718720201': 5, 'Guess': 5, 'YOUR': 5, 'b': 5, 'why': 5, 'onto': 5, 'http://www.urawinner.com': 5, 'awaiting': 5, 'part': 5, 'club': 5, 'first': 5, 'LIVE': 5, '20p': 5, '1327': 5, 'Croydon': 5, 'CR9': 5, '5WB': 5, 'one': 5, 'reach': 5, 'ASAP!': 5, 'B': 5, '0870': 5, 'Now': 5, 'Auction': 5, 'Choose': 5, 'BT-national-rate': 5, 'rate)': 5, '@': 5, 'Del': 5, 'order,': 5, 'Should': 5, 'message.': 5, 'friend': 5, 'minute.': 5, 'great': 5, 'XMAS': 5, 'POLY': 5, 'Welcome': 5, 'Price': 5, 'TEXT': 5, '3510i': 5, 'minutes': 5, 'hours': 4, 'POBOX': 4, 'England': 4, 'miss': 4, 'Ringtone': 4, 'nokia': 4, 'SMS.': 4, 'ac': 4, 'Congrats!': 4, 'yours.': 4, 'customer,': 4, 'following': 4, 'weekends': 4, 'speak': 4, '2004': 4, 'app': 4, 'Sunshine': 4, 'Quiz': 4, 'DVD': 4, 'largest': 4, 'ec2a.': 4, 'Why': 4, 'Netcollex': 4, 'Ltd': 4, 'her:': 4, 'FREEPHONE': 4, '2optout': 4, 'meet': 4, 'partner': 4, 'its': 4, 'NAME': 4, 'admirer': 4, 'Camcorder?': 4, 'Club:': 4, 'HMV': 4, 'Now!': 4, 'More': 4, 'ends': 4, 'Check': 4, 'selection': 4, 'only!': 4, 'update': 4, 'over': 4, '150p/msg': 4, 'msg.': 4, 'X': 4, 'Offer!': 4, '1000': 4, 'Orange.': 4, 'calling': 4, 'Motorola': 4, 'half': 4, 'poly': 4, 'GET': 4, 'after': 4, 'LOVE': 4, 'POBox36504W45WQ': 4, 'fancy': 4, 'Calls': 4, 'still': 4, 'award!': 4, 'CW25WX': 4, 'Phone,': 4, 'COLLECT': 4, 'credits': 4, '85023': 4, 'SavaMob,': 4, '£3.00': 4, 'within': 4, 'us': 4, 'TXT:': 4, "T's&C's": 4, 'FROM': 4, 'Holder,': 4, 'offer,': 4, 'PC': 4, '<Forwarded': 4, '10am-7pm': 4, 'TC': 4, 'best': 4, '£3': 4, 'Break': 4, 'Shopping': 4, 'STORE': 4, 'good': 4, 'SavaMob': 4, '36504': 4, 'were': 4, 'www.comuk.net': 4, 'zed': 4, '80062': 4, 'Phone': 4, 'service.': 4, 'VIP': 4, 'CDs': 4, 'user': 4, 'Can': 4, 'games': 4, 'getting': 4, 'games,': 4, 'local': 4, 'DATE': 4, 'asked': 4, 'revealed.': 4, "U've": 4, 'invited': 4, 'u!': 4, 'information': 4, 'O2': 4, 'log': 4, 'place': 4, 'me.': 4, 'girls': 4, 'ready': 4, 'gay': 4, 'wanna': 4, 'tone,': 4, '08707509020': 4, 'FANTASTIC': 4, '02/06/03!': 4, 'day': 4, '2day': 4, 'x': 4, 'BT': 4, '86021': 4, 'plus': 4, '250': 4, 'rply': 4, 'got': 4, 'last': 4, '08001950382': 4, 'XXX': 4, 'TO': 4, 'THE': 4, 'Im': 4, 'Costa': 4, 'Sol': 4, '87239': 4, 'FreeMsg:': 4, 'ntwk': 4, 'babe': 4, 'unlimited': 4, 'weekend': 4, 'polys': 4, 'sex': 4, 'tariffs.': 4, 'Camcorder': 4, 'talk': 4, 'URGENT': 4, 'cancel': 4, 'Santa': 4, '12': 3, '11': 3, 'Free!': 3, 'HL': 3, 'click': 3, 'subscription': 3, 'sms': 3, 'END': 3, 'review': 3, 'Prize,': 3, 'trip': 3, 'hear': 3, 'comes': 3, 'Code': 3, '(flights': 3, 'inc)': 3, '(18+)': 3, '786': 3, 'unredeemed': 3, 'try': 3, 'Sony': 3, '82277.': 3, 'laid': 3, 'wap.': 3, 'Find': 3, 'Mobiles': 3, '2004,': 3, 'MUST': 3, 'GO!': 3, '89545': 3, 'www.4-tc.biz': 3, '087187262701.50gbp/mtmsg18': 3, 'Will': 3, 'followed': 3, 'date': 3, 'pence': 3, 'TEXT?': 3, 'Go': 3, 'choose': 3, 'singles': 3, 'Play': 3, 'CAMERA': 3, 'PHONE': 3, 'upgrade': 3, 'loyalty.': 3, '0845': 3, 'sms.': 3, 'newest': 3, 'M26': 3, '16+.': 3, 'December': 3, '11mths+?': 3, 'Germany': 3, 'via': 3, 'Day': 3, '83600': 3, 'rcvd.': 3, 'Row/W1J6HL': 3, 'further': 3, 'stop.': 3, 'week.': 3, '11mths': 3, 'RINGTONE': 3, '87131': 3, 'Help?': 3, 'logo': 3, '3mins': 3, 'vary': 3, 'Have': 3, 'Opt-out': 3, 'notice': 3, '#5000': 3, '83355!': 3, 'IBHltd': 3, 'LdnW15H': 3, '3.': 3, 'BOX95QU': 3, 'member': 3, 'Sub.': 3, 'Terms': 3, 'S.I.M.': 3, 'age16': 3, 'claim,': 3, 'calls': 3, 'shopping': 3, 'announcement.': 3, '542': 3, 'daily.': 3, 'guys': 3, 'postcode': 3, 'ONE': 3, '20': 3, 'work': 3, 'fantastic': 3, 'game': 3, 'Club': 3, 'Loyalty': 3, '£10': 3, 'subscribed': 3, 'Content': 3, 'City': 3, 'Summer': 3, 'WK.': 3, 'SkilGme.': 3, 'W45WQ': 3, 'norm150p/tone': 3, 'credits,': 3, 'goto': 3, 'login=': 3, '3qxj9': 3, 'help': 3, '9AE': 3, "Moon's": 3, 'Children': 3, 'song': 3, 'mob.': 3, 'Tell': 3, 'm8s.': 3, 'Poly': 3, '08701417012': 3, 'profit': 3, 'care': 3, 'five': 3, 'Ibiza': 3, 'ppm': 3, 'yrs': 3, 'Gift': 3, 'GUARANTEED': 3, 'address': 3, 'What': 3, '(10p/min)': 3, '114/14': 3, 'TCR/W1': 3, '3G': 3, 'Videophones': 3, 'videochat': 3, 'wid': 3, 'mates,': 3, 'java': 3, 'Dload': 3, 'music,': 3, 'noline': 3, 'rentl.': 3, 'mates': 3, 'fancies': 3, '150p/min': 3, 'people': 3, 'registered': 3, 'Cant': 3, 'who?': 3, 'XCHAT.': 3, 'SiPix': 3, 'Digital': 3, 'Camera!': 3, 'Delivery': 3, '150ppm.': 3, 'valid': 3, 'receipt': 3, 'correct': 3, 'When': 3, "don't": 3, 'many': 3, 'Luck!': 3, 'takes': 3, 'Sex': 3, 'pic': 3, '£3/wk': 3, 'store': 3, '08712405020.': 3, 'cum': 3, 'here': 3, 'xx': 3, 'free.': 3, 'www.ringtones.co.uk,': 3, 'original': 3, 'best.': 3, '3GBP': 3, 'question': 3, 'HOT': 3, 'FANTASIES': 3, 'photo': 3, '1/2': 3, 'IMPORTANT': 3, 'SURPRISE': 3, 'AWAITING': 3, '150p/MsgrcvdHG/Suite342/2Lands/Row/W1J6HL': 3, 'LDN': 3, 'wk.': 3, 'POD': 3, 'ans': 3, 'alone': 3, '09066362231': 3, 'account': 3, 'auction.': 3, 'AUCTION': 3, 'auction': 3, 'Need': 3, 'credit': 3, 'stay': 3, 'London': 3, '82242': 3, 'b4': 3, 'ordered': 3, '60p/min.': 3, 'before': 3, 'Games': 3, '(std': 3, 'computer': 3, 'Pound': 3, 'min.': 3, 'Would': 3, 'ABTA': 3, 'IN': 3, 'xxx': 3, '09050090044': 3, 'toClaim.': 3, 'SAE,': 3, 'POBox334,': 3, 'Stockport,': 3, 'SK38xh,': 3, 'Cost£1.50/pm,': 3, 'Max10mins': 3, 'downloads': 3, 'Speak': 3, '***********': 3, 'BOX97N7QP,': 3, 'etc.': 3, 'REAL': 3, 'official': 3, 'inclusive': 3, 'cross': 3, '£4.50.': 3, '1000s': 3, '88066': 3, 'HELP': 3, 'calls.': 3, 'alert.': 3, 'SP': 3, '80082': 3, '09066612661': 3, 'CHANCE': 3, 'how': 3, 'Sept': 3, 'little': 3, 'crazy': 3, '6': 3, 'PORN': 3, 'reference': 3, '4.50.': 3, 'DeliveredTomorrow?': 3, '300': 3, 'know!': 3, 'is,': 3, 'time.': 3, 'billed': 3, 'night': 3, 'inc': 3, '200': 3, 'handset?': 3, '£400': 3, "THERE'S": 3, 'records': 3, 'contract': 3, 'FA': 2, 'Cup': 2, 'tkts': 2, '2005.': 2, '87121': 2, 'darling': 2, "it's": 2, "week's": 2, "I'd": 2, 'XxX': 2, 'std': 2, 'rcv': 2, 'reward!': 2, 'Co': 2, '87575.': 2, 'CLAIM': 2, 'v': 2, 'ENGLAND': 2, 'NO': 2, 'MSG': 2, 'End?': 2, 'year': 2, 'special': 2, 'pass': 2, 'etc': 2, 'Dont': 2, 'out!': 2, 'pleased': 2, 'advise': 2, 'recent': 2, 'Mob': 2, '£1500': 2, 'Or': 2, 'It': 2, 'password': 2, 'Points.': 2, '45239': 2, 'U!': 2, '150PPM': 2, 'Wkly': 2, 'Q!': 2, 'country': 2, 'ansr': 2, 'SP:Tyrone': 2, 'tonight?': 2, 'Network': 2, '31p.msg@150p': 2, 'msgs': 2, 'nothing': 2, 'must': 2, '08700621170150p': 2, 'Years': 2, 'arrange': 2, 'Msg': 2, 'download': 2, 'unique': 2, 'today!From': 2, '£1': 2, 'off': 2, 'free,': 2, 'HORO': 2, 'e.': 2, 'g.': 2, 'today.': 2, 'flirt': 2, '125gift': 2, 'www.Ldew.com1win150ppmx3age16': 2, 'Handset?': 2, 'networks': 2, '69698': 2, '150pm': 2, '25': 2, 'Stop?': 2, 'CLUB': 2, 'MK45': 2, '2WT': 2, 'quality': 2, 'T-Mobile': 2, '021': 2, 'Blind': 2, 'babes': 2, 'sport,': 2, '82468': 2, 'Think': 2, 'PLAY': 2, '08002986906': 2, 'minute!': 2, 'fixed': 2, '0844': 2, '861': 2, '85': 2, '85.': 2, 'prepayment.': 2, 'Direct': 2, 'access!': 2, 'Valentines': 2, 'Special!': 2, 'quiz': 2, 'lifetime!': 2, '1.50': 2, 'Update_Now': 2, '4mths': 2, 'MobilesDirect': 2, '08000938767': 2, 'or2stoptxt': 2, '80086': 2, 'www.txttowin.co.uk': 2, 'lover': 2, 'names': 2, 'joined': 2, 'heart.': 2, 'NAME1': 2, 'NAME2': 2, 'MOBNO': 2, 'ADAM': 2, 'EVE': 2, '07123456789': 2, 'Yahoo!': 2, 'TxtNO': 2, 'ads': 2, 'because': 2, 'WC1N3XX': 2, 'purpose': 2, 'Tenants': 2, "'help'": 2, '0207': 2, '153': 2, 'Dave': 2, '09061743806': 2, 'TCs': 2, 'Box326': 2, 'Activate': 2, 'terms': 2, '1.': 2, 'Cha': 2, '2.': 2, '02/09/03!': 2, "Today's": 2, '08717898035.': 2, 'Unsub': 2, 'conditions': 2, '08718738001': 2, 'web': 2, '?1,000': 2, '?2,000': 2, 'claims': 2, 'SHOP': 2, '08715705022,': 2, '1x150p/wk': 2, 'pound': 2, '08712402050': 2, 'BEFORE': 2, 'lines': 2, 'close.': 2, '10ppm.': 2, 'AG': 2, 'Promo': 2, 'ALL': 2, 'kick': 2, 'off!': 2, 'Euro2004': 2, 'kept': 2, 'results': 2, 'TEXTBUDDY': 2, 'Search': 2, 'gaytextbuddy.com.': 2, 'Vodafone': 2, 'http://www.e-tlp.co.uk/expressoffer': 2, '40533': 2, '31/10/04': 2, 'T&C:': 2, 'RSTM,': 2, 'SW7': 2, '3SS.': 2, 'premium': 2, 'years': 2, 'old': 2, 'KEEP': 2, 'Offer:The': 2, 'Nokia6650': 2, 'TXTAUCTION!': 2, 'START': 2, '81151': 2, '4T&Ctxt': 2, '150p/MTmsg': 2, 'Helpline': 2, '40': 2, "we'll": 2, 'around': 2, 'announcement': 2, 'PREMIER.': 2, 'flights': 2, '88039': 2, 'TsCs087147403231Winawk!Age16': 2, '£1.50perWKsub': 2, '0578': 2, 'life': 2, 'Top': 2, 'SUBPOLY': 2, 'Chance!': 2, 'POBOX84,': 2, 'M263UZ.': 2, 'mates.': 2, 'cashto': 2, '08000407165': 2, 'getstop': 2, '88222': 2, 'STOP,': 2, '08702840625.COMUK.': 2, '220-CM2': 2, 'alfie': 2, 'Nokias': 2, 'polys:': 2, 'charity.': 2, 'REVEAL': 2, '08002888812': 2, 'Rental': 2, 'Remove': 2, '434': 2, 'SK3': 2, '8WP': 2, 'Make': 2, 'most': 2, 'discreet': 2, 'supply': 2, 'www.smsco.net': 2, '41685': 2, '07/11/04': 2, 'rental?': 2, 'till': 2, 'Cash': 2, 'Liverpool': 2, '09058094565': 2, 'Secret': 2, 'Admirer': 2, 'Click': 2, 'Male': 2, 'Sale!': 2, 'Hot': 2, 'Gay': 2, 'cheaper,': 2, '08709222922.': 2, '1.5p/min': 2, 'cheap': 2, '7.8p/min': 2, 'peak!': 2, 'money': 2, '88600': 2, 'landline,': 2, 'Landline.': 2, 'Valid12hrs': 2, '09063458130': 2, 'what!': 2, 'Somebody': 2, 'secretly': 2, 'is?': 2, 'Give': 2, 'DATEBox1282EssexCM61XN': 2, '6,': 2, 'LS15HB': 2, "1000's": 2, 'GIRL': 2, 'Unsubscribe': 2, 'does': 2, 'F': 2, '84025': 2, 'start': 2, '09050003091': 2, 'C52.': 2, '09061790121': 2, 'Subscriber': 2, 'ans.': 2, 'Important': 2, 'user.': 2, 'Today': 2, 'day!': 2, 'surprise': 2, 'Bored': 2, 'Try': 2, '08000776320': 2, 'wish.': 2, 'forget': 2, "let's": 2, 'future': 2, '4fil': 2, 'Then': 2, 'PocketBabe.co.uk': 2, 'voicemail.': 2, 'delivered': 2, 'OK': 2, 'claim.': 2, '87021.': 2, 'txtin': 2, 'friends.': 2, '150p/tone.': 2, '4info': 2, 'RECEIVE': 2, 'ENTER': 2, '84128': 2, 'www.textcomp.com': 2, 'feeling': 2, '10p/min.': 2, 'Calls£1/minmoremobsEMSPOBox45PO139WA': 2, "C's": 2, 'Lions': 2, 'lionm': 2, 'mono': 2, 'lionp': 2, 'poly.': 2, 'Potter': 2, 'Order': 2, 'Phoenix': 2, '(Book': 2, '5)': 2, 'HARRY,': 2, 'questions': 2, 'among': 2, 'readers!': 2, 'balance': 2, 'luck!': 2, 'saucy': 2, 'c': 2, 'In': 2, 'upload': 2, '08718730666': 2, '(10p/min).': 2, 'INFORMATION': 2, 'TODAY': 2, 'LUCKY': 2, 'FIND': 2, 'WHY': 2, 'LOG': 2, 'ONTO': 2, 'sale': 2, 'TEXTPOD': 2, 'www.textpod.net': 2, 'OptOut': 2, 'CLAIRE': 2, '2nite?': 2, 'hope': 2, 'costing': 2, '07xxxxxxxxx': 2, 'bonus': 2, 'caller': 2, 'Fri': 2, 'Pls': 2, 'leave': 2, 'Calls£1/minMobsmoreLKPOBOX177HP51FL': 2, '80488': 2, 'mobile.': 2, 'brand': 2, 'music': 2, 'shortly.': 2, 'Rate': 2, '7250i.': 2, 'Row/W1JHL': 2, 'Hello': 2, 'YES.': 2, 'BRAND': 2, '7250': 2, 'part!': 2, 'ok': 2, 'British': 2, 'hotels': 2, 'NOTHING!': 2, '£350!': 2, 'SW73SS': 2, 'TITLE': 2, 'Titles:': 2, 'bill': 2, 'B.': 2, 'G.': 2, 'keep': 2, 'cam': 2, 'Msg150p': 2, '2rcv': 2, 'Hlp': 2, '08712317606': 2, 'ACTION': 2, '80608.': 2, 'www.movietrivia.tv': 2, '08712405022,': 2, 'U!U': 2, 'max£7.': 2, '50': 2, 'wiv': 2, 'Am': 2, 'Use': 2, 'vodafone': 2, 'received': 2, '81303': 2, 'credit.': 2, '121': 2, 'biggest': 2, '2007': 2, 'Tickets': 2, 'Hi,': 2, 'GOING': 2, 'Buy': 2, 'Arcade': 2, 'Press': 2, '0': 2, 'settings.': 2, 'purchase': 2, 'exciting': 2, '3100': 2, 'straight': 2, '89555': 2, 'textoperator': 2, 'g696ga': 2, 'upto': 2, '18yrs': 2, '326': 2, 'U,': 2, 'these': 2, '(18': 2, 'ipod.': 2, '80182': 2, '08452810073': 2, 'tells': 2, '09066358152': 2, 'personal': 2, 'prompts.': 2, 'Careful!': 2, 'dogging': 2, 'guys.': 2, 'weekly!': 2, 'Hope': 2, 'enjoyed': 2, '61610': 2, 'unsubscribe.': 2, 'help:08712400602450p': 2, 'Provided': 2, 'tones2you.co.uk': 2, 'Great': 2, 'News!': 2, 'Music': 2, 'Vouchers': 2, 'starting': 2, 'DRAW': 2, 'TsCs': 2, '10p/min': 2, 'GENDER': 2, 'flag': 2, 'yer': 2, 'FLAG': 2, 'ENG': 2, 'Box39822': 2, 'W111WX': 2, 'Final': 2, 'SERVICES.': 2, 'satisfy': 2, 'linerental': 2, 'mins.': 2, 'also': 2, 's,': 2, 'ref': 2, 'term': 2, 'B4': 2, 'gr8': 2, 'Not': 2, 'heard': 2, 'U4': 2, 'while.': 2, 'rude': 2, 'LOST': 2, 'Oranges': 2, 'Upd8': 2, 'freefone': 2, '21870000>Hi': 2, 'Mailbox': 2, 'Messaging': 2, 'matches.': 2, '09056242159': 2, 'retrieve': 2, 'Moby': 2, 'Pub': 2, 'Quiz.Win': 2, 'High': 2, 'Street': 2, 'Duchess': 2, 'Cornwall': 2, 'be?': 2, '82277.unsub': 2, '008704050406': 2, 'Congratulations!': 2, 'BT-national-rate.': 2, 'ringtones': 2, 'Halloween': 2, 'eerie': 2, 'CARD': 2, 'SPOOK': 2, 'Sky': 2, 'adult': 2, 'UK.': 2, 'charge': 2, '1x150p/wk.': 2, '24': 2, 'ACL03530150PM': 2, 'Ltd.': 2, 'bx420.': 2, 'ip4.': 2, '5we.': 2, 'amazing': 2, 'PICSFREE1': 2, 'Msgs': 2, 'follow': 2, 'Knock': 2, '150p/Mtmsgrcvd18': 2, 'look': 2, 'norm': 2, 'mobile?': 2, '69696': 2, '3lp': 2, 'fone': 2, 'hit': 2, 'include:': 2, '2)': 2, '3)': 2, 'sports': 2, 'away,': 2, 'UKs': 2, 'fastest': 2, 'growing': 2, 'rcvd': 2, 'DOUBLE': 2, 'AND': 2, 'luxury': 2, 'Canary': 2, 'Islands': 2, 'Burger': 2, 'King': 2, 'Player': 2, 'since': 2, 'warm': 2, '150p.': 2, 'BE': 2, 'REALITY': 2, 'FANTASY': 2, 'SHOW': 2, 'phone?': 2, '50p': 2, 'than': 2, 'sport': 2, 'POLYPHONIC': 2, 'improved': 2, 'club!': 2, 'msgs@150p': 2, 'phone!': 2, 'u?': 2, 'visionsms.com': 2, 'OF': 2, 'LOTR': 2, 'removal': 2, '08708034412': 2, '08000930705.': 2, 'Camera': 2, '09061221066': 2, 'fromm': 2, '28': 2, 'text.': 2, 'PoBox45W2TG150P': 2, 'charges': 2, 'truly': 2, "won't": 2, 'enjoy': 2, 'mths?': 2, 'Save': 2, 'days.': 2, 'Its': 2, 'films': 2, '(Bank': 2, 'Granite': 2, 'issues': 2, 'Strong-Buy)': 2, 'EXPLOSIVE': 2, 'PICK': 2, 'OUR': 2, 'MEMBERS': 2, '*****UP': 2, 'OVER': 2, '300%': 2, 'Nasdaq': 2, 'Symbol': 2, 'CDGT': 2, 'That': 2, '$5.00': 2, 'per..': 2, 'Sat': 2, '3UZ': 2, '4.': 2, 'Next': 2, 'PARIS': 2, 'Colour': 2, 'Delivered': 2, 'Tomorrow?': 2, 'CHARITY': 2, 'recently': 2, 'unable': 2, 'so,': 2, 're-schedule.': 2, 'class': 2, 'using': 2, "Don't": 2, "weekend's": 2, 'iscoming': 2, 'TnC': 2, 'Blu': 2, 'Msg:': 2, 'widelive.com/index.': 2

In [15]:
hamOnly = df[df.Category=="ham"]
hamWordCount = hamOnly["Message"].str.split().explode().value_counts()
hamWordCount

Message
to                 1457
you                1416
I                  1352
the                 964
a                   892
                   ...
exam.                 1
nmde                  1
dental                1
4years                1
Pshew...missing       1
Name: count, Length: 12582, dtype: int64

In [16]:
df['Category'] = df['Category'].map({'ham': 0, 'spam': 1})
df.rename(columns={'Category': 'spam'}, inplace=True)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_13196\625275476.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Category'] = df['Category'].map({'ham': 0, 'spam': 1})
C:\Users\ASUS\AppData\Local\Temp\ipykernel_13196\625275476.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={'Category': 'spam'}, inplace=True)

In [17]:
df

,spam,Message,charCount,wordCount,digitCount,urlCount,currencyCount,exclamationCount
0,0,"Go until jurong point, crazy.. Available only ...",111,20,0,0,0,0
1,0,Ok lar... Joking wif u oni...,29,6,0,0,0,0
2,1,Free entry in 2 a wkly comp to win FA Cup fina...,155,28,25,0,0,0
3,0,U dun say so early hor... U c already then say...,49,11,0,0,0,0
4,0,"Nah I don't think he goes to usf, he lives aro...",61,13,0,0,0,0
...,...,...,...,...,...,...,...,...
5567,1,This is the 2nd time we have tried 2 contact u...,160,30,21,0,1,1
5568,0,Will ü b going to esplanade fr home?,36,8,0,0,0,0
5569,0,"Pity, * was in mood for that. So...any other s...",57,10,0,0,0,0
5570,0,The guy did some bitching but I acted like i'd...,125,26,0,0,0,0
5571,0,Rofl. Its true to its name,26,6,0,0,0,0

In [18]:
from sklearn.model_selection import train_test_split

target = df['spam']
df.drop(columns=['spam'],inplace=True)

xTrain, xTest, yTrain, yTest = train_test_split(df,target,test_size=0.25,random_state=42,stratify=target)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_13196\661268128.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=['spam'],inplace=True)

In [19]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
from scipy.sparse import hstack
from sklearn.preprocessing import MinMaxScaler


tfV = TfidfVectorizer()
xTrainCount = tfV.fit_transform(xTrain['Message'])
extraFeatures = xTrain[
    ['charCount',
     'wordCount',
     'digitCount',
     'urlCount',
     'currencyCount',
     'exclamationCount']
]

# xTrainFinal = hstack([xTrainCount, extraFeatures])


xTestCount = tfV.transform(xTest["Message"])

extraTest = xTest[
    ['charCount',
     'wordCount',
     'digitCount',
     'urlCount',
     'currencyCount',
     'exclamationCount']
]

# xTestFinal = hstack([xTestCount, extraTest])



scaler = MinMaxScaler()

extraTrain = scaler.fit_transform(extraFeatures)
extraTest = scaler.transform(extraTest)


xTrainFinal = hstack([xTrainCount, extraTrain])
xTestFinal = hstack([xTestCount, extraTest])

model = MultinomialNB()

model.fit(xTrainFinal,yTrain)

pred = model.predict(xTestFinal)

accuracy_score(yTest, pred)

0.9682170542635659

In [20]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

print(classification_report(yTest, pred))
print(confusion_matrix(yTest, pred))

              precision    recall  f1-score   support

           0       0.96      1.00      0.98      1130
           1       1.00      0.74      0.85       160

    accuracy                           0.97      1290
   macro avg       0.98      0.87      0.92      1290
weighted avg       0.97      0.97      0.97      1290

[[1130    0]
 [  41  119]]

In [21]:
countV = CountVectorizer()
xTrainCount = countV.fit_transform(xTrain['Message'])
extraFeatures = xTrain[
    ['charCount',
     'wordCount',
     'digitCount',
     'urlCount',
     'currencyCount',
     'exclamationCount']
]

# xTrainFinal = hstack([xTrainCount, extraFeatures])


xTestCount = countV.transform(xTest["Message"])

extraTest = xTest[
    ['charCount',
     'wordCount',
     'digitCount',
     'urlCount',
     'currencyCount',
     'exclamationCount']
]

# xTestFinal = hstack([xTestCount, extraTest])
scaler = MinMaxScaler()

extraTrain = scaler.fit_transform(extraFeatures)
extraTest = scaler.transform(extraTest)

xTrainFinal = hstack([xTrainCount, extraTrain])
xTestFinal = hstack([xTestCount, extraTest])

model = MultinomialNB()

model.fit(xTrainFinal,yTrain)
# model.fit(xTrainFinal,yTrain)

pred = model.predict(xTestFinal)

# accuracy_score(yTest, pred)

emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!',
    'Get free million dollar prize in seconds sign up now !',
    'Games are waiting for you play games like playing in heaven !! dont miss this, see you soon',
    'Congratulations! You won a FREE iPhone. Click here to claim your prize now. Limited time offer.'
]
searchDf = pd.DataFrame(emails,columns=['Message'])
searchMessageCount = countV.transform(emails)

searchDf['charCount'] = searchDf['Message'].str.len()
searchDf['wordCount'] = searchDf['Message'].str.split().str.len()
searchDf["digitCount"] = searchDf['Message'].str.count(r"\d")
searchDf["urlCount"] = searchDf['Message'].str.count(r"http|www")
searchDf["currencyCount"] = searchDf['Message'].str.count(r"£|\$|₹")
searchDf["exclamationCount"] = searchDf['Message'].str.count("!")
extraSearchTest = searchDf[
    ['charCount',
     'wordCount',
     'digitCount',
     'urlCount',
     'currencyCount',
     'exclamationCount']
]
extraSearchTest = scaler.transform(extraSearchTest)
searchFinal = hstack([searchMessageCount, extraSearchTest])
model.predict(searchFinal)

array([0, 1, 1, 0, 1])

In [22]:
for word in ["games", "heaven", "play", "free", "prize", "claim"]:
    print(word, countV.vocabulary_.get(word))

games 2913
heaven None
play 4971
free 2834
prize 5148
claim 1761

In [23]:
np.set_printoptions(suppress=True)
print(np.round(model.predict_proba(searchFinal), 4))

[[1.     0.    ]
 [0.0743 0.9257]
 [0.024  0.976 ]
 [0.9996 0.0004]
 [0.     1.    ]]

In [24]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

print(classification_report(yTest, pred))
print(confusion_matrix(yTest, pred))

              precision    recall  f1-score   support

           0       0.98      0.99      0.99      1130
           1       0.96      0.89      0.92       160

    accuracy                           0.98      1290
   macro avg       0.97      0.94      0.96      1290
weighted avg       0.98      0.98      0.98      1290

[[1124    6]
 [  18  142]]

In [ ]:
feature_names = countV.get_feature_names_out()

importance = model.feature_log_prob_[1] - model.feature_log_prob_[0]

spam_scores = dict(zip(feature_names, importance))

In [35]:
for i in spam_scores:
    print(i + " : ",spam_scores[i]) 
# spam_scores

00 :  2.620310901450406
000 :  3.9553119681827464
000pes :  0.3177258084563608
008704050406 :  1.7040201695762516
01223585236 :  1.7040201695762516
01223585334 :  1.7040201695762516
0125698789 :  0.3177258084563608
02 :  3.0903145306961424
0207 :  2.397167350136197
02072069400 :  1.7040201695762516
02085076972 :  1.7040201695762516
021 :  1.7040201695762516
03 :  3.495779638804306
04 :  3.0903145306961424
0430 :  1.7040201695762516
05 :  2.620310901450406
050703 :  1.7040201695762516
0578 :  2.1094852776844153
06 :  3.208097566352526
07 :  1.7040201695762516
07090201529 :  1.7040201695762516
07090298926 :  1.7040201695762516
07099833605 :  1.7040201695762516
07123456789 :  1.7040201695762516
0721072 :  1.7040201695762516
07732584351 :  1.7040201695762516
07734396839 :  1.7040201695762516
07742676969 :  1.7040201695762516
07753741225 :  1.7040201695762516
0776xxxxxxx :  1.7040201695762516
07781482378 :  1.7040201695762516
07786200117 :  1.7040201695762516
077xxx :  1.7040201695762516
078 :  1.7040201695762516
07801543489 :  1.7040201695762516
07808247860 :  1.7040201695762516
07808726822 :  1.7040201695762516
07821230901 :  1.7040201695762516
078498 :  1.7040201695762516
07880867867 :  1.7040201695762516
0789xxxxxxx :  1.7040201695762516
07946746291 :  1.7040201695762516
07973788240 :  1.7040201695762516
07xxxxxxxxx :  2.397167350136197
08 :  2.1094852776844153
0800 :  3.313458082010352
08000407165 :  1.7040201695762516
08000776320 :  2.1094852776844153
08000839402 :  3.408768261814677
08000930705 :  3.408768261814677
08000938767 :  2.1094852776844153
08001950382 :  2.620310901450406
08002888812 :  2.1094852776844153
08002986030 :  1.7040201695762516
08002986906 :  1.7040201695762516
08002988890 :  1.7040201695762516
0808 :  1.7040201695762516
08081263000 :  1.7040201695762516
08081560665 :  1.7040201695762516
0825 :  1.7040201695762516
083 :  1.7040201695762516
0844 :  2.1094852776844153
08448350055 :  1.7040201695762516
0845 :  2.1094852776844153
08450542832 :  1.7040201695762516
08452810071 :  1.7040201695762516
08452810075over18 :  1.7040201695762516
0870 :  2.397167350136197
08700469649 :  1.7040201695762516
08700621170150p :  1.7040201695762516
08701213186 :  1.7040201695762516
08701237397 :  1.7040201695762516
08701417012 :  2.1094852776844153
08701417012150p :  1.7040201695762516
0870141701216 :  1.7040201695762516
087016248 :  1.7040201695762516
08701752560 :  1.7040201695762516
087018728737 :  1.7040201695762516
0870241182716 :  1.7040201695762516
08702840625 :  2.1094852776844153
08704050406 :  1.7040201695762516
08704439680 :  1.7040201695762516
08704439680ts :  1.7040201695762516
08706091795 :  1.7040201695762516
0870737910216yrs :  1.7040201695762516
08707500020 :  1.7040201695762516
08707509020 :  2.1094852776844153
0870753331018 :  1.7040201695762516
08707808226 :  1.7040201695762516
08708034412 :  2.1094852776844153
08708800282 :  1.7040201695762516
08709501522 :  1.7040201695762516
0871 :  2.1094852776844153
087104711148 :  1.7040201695762516
08712101358 :  1.7040201695762516
08712103738 :  1.7040201695762516
0871212025016 :  1.7040201695762516
08712300220 :  2.8026324582443607
087123002209am :  1.7040201695762516
08712317606 :  1.7040201695762516
08712400602450p :  1.7040201695762516
08712400603 :  1.7040201695762516
08712402050 :  2.1094852776844153
08712402578 :  1.7040201695762516
08712402779 :  1.7040201695762516
08712402902 :  1.7040201695762516
08712402972 :  1.7040201695762516
08712404000 :  1.7040201695762516
08712405020 :  2.397167350136197
08712405022 :  2.1094852776844153
08712460324 :  2.8026324582443607
08712466669 :  1.7040201695762516
0871277810710p :  1.7040201695762516
0871277810810 :  1.7040201695762516
08714712379 :  1.7040201695762516
08714712388 :  1.7040201695762516
08714712394 :  1.7040201695762516
08714712412 :  1.7040201695762516
08714714011 :  1.7040201695762516
08715203028 :  1.7040201695762516
08715203649 :  1.7040201695762516
08715203652 :  1.7040201695762516
08715203677 :  1.7040201695762516
08715203685 :  1.7040201695762516
08715205273 :  1.7040201695762516
08715500022 :  1.7040201695762516
08715705022 :  2.1094852776844153
08717111821 :  1.7040201695762516
08717168528 :  1.7040201695762516
08717509990 :  1.7040201695762516
08717895698 :  1.7040201695762516
08717898035 :  1.7040201695762516
08718711108 :  1.7040201695762516
08718720201 :  2.8026324582443607
08718723815 :  1.7040201695762516
08718725756 :  1.7040201695762516
08718726270 :  1.7040201695762516
087187262701 :  2.397167350136197
08718726970 :  1.7040201695762516
08718726971 :  1.7040201695762516
08718727870 :  2.397167350136197
08718727870150ppm :  1.7040201695762516
08718730555 :  1.7040201695762516
08718730666 :  2.1094852776844153
08718738001 :  1.7040201695762516
08718738002 :  1.7040201695762516
08718738034 :  1.7040201695762516
08719180219 :  1.7040201695762516
08719180248 :  1.7040201695762516
08719181259 :  1.7040201695762516
08719181503 :  1.7040201695762516
08719181513 :  1.7040201695762516
08719839835 :  1.7040201695762516
08719899229 :  1.7040201695762516
08719899230 :  1.7040201695762516
09 :  2.1094852776844153
09050000301 :  1.7040201695762516
09050000332 :  1.7040201695762516
09050000460 :  1.7040201695762516
09050000878 :  1.7040201695762516
09050000928 :  1.7040201695762516
09050001295 :  1.7040201695762516
09050001808 :  1.7040201695762516
09050005321 :  1.7040201695762516
09050090044 :  2.397167350136197
09050280520 :  1.7040201695762516
09053750005 :  1.7040201695762516
09056242159 :  1.7040201695762516
09057039994 :  1.7040201695762516
09058091854 :  1.7040201695762516
09058091870 :  1.7040201695762516
09058094455 :  1.7040201695762516
09058094507 :  1.7040201695762516
09058094565 :  2.1094852776844153
09058094583 :  1.7040201695762516
09058094594 :  1.7040201695762516
09058094597 :  1.7040201695762516
09058094599 :  1.7040201695762516
09058097189 :  1.7040201695762516
09058097218 :  1.7040201695762516
09058098002 :  1.7040201695762516
09058099801 :  1.7040201695762516
09061104283 :  1.7040201695762516
09061209465 :  1.7040201695762516
09061213237 :  2.1094852776844153
09061221061 :  1.7040201695762516
09061221066 :  2.1094852776844153
09061701444 :  1.7040201695762516
09061701851 :  1.7040201695762516
09061701939 :  1.7040201695762516
09061702893 :  2.1094852776844153
09061743386 :  1.7040201695762516
09061743806 :  2.1094852776844153
09061743810 :  1.7040201695762516
09061749602 :  1.7040201695762516
09061790121 :  1.7040201695762516
09061790125 :  1.7040201695762516
09063440451 :  1.7040201695762516
09063458130 :  2.1094852776844153
09064011000 :  1.7040201695762516
09064012160 :  1.7040201695762516
09064015307 :  1.7040201695762516
09064017295 :  1.7040201695762516
09064017305 :  1.7040201695762516
09064018838 :  1.7040201695762516
09064019014 :  1.7040201695762516
09064019788 :  1.7040201695762516
09065069120 :  1.7040201695762516
09065069154 :  1.7040201695762516
09065171142 :  2.1094852776844153
09065174042 :  1.7040201695762516
09065394514 :  1.7040201695762516
09065394973 :  1.7040201695762516
09065989180 :  1.7040201695762516
09065989182 :  2.1094852776844153
09066350750 :  1.7040201695762516
09066358152 :  1.7040201695762516
09066358361 :  1.7040201695762516
09066362206 :  1.7040201695762516
09066362220 :  1.7040201695762516
09066362231 :  2.397167350136197
09066364311 :  1.7040201695762516
09066364589 :  1.7040201695762516
09066368327 :  1.7040201695762516
09066368470 :  1.7040201695762516
09066368753 :  1.7040201695762516
09066380611 :  1.7040201695762516
09066382422 :  1.7040201695762516
09066612661 :  2.1094852776844153
09066649731from :  1.7040201695762516
09066660100 :  1.7040201695762516
09071512432 :  1.7040201695762516
09071512433 :  1.7040201695762516
09071517866 :  1.7040201695762516
09090204448 :  1.7040201695762516
09090900040 :  1.7040201695762516
09094100151 :  1.7040201695762516
09094646631 :  1.7040201695762516
09094646899 :  1.7040201695762516
09099725823 :  1.7040201695762516
09099726429 :  1.7040201695762516
09099726481 :  1.7040201695762516
09701213186 :  1.7040201695762516
0a :  1.7040201695762516
10 :  1.4163380971244708
100 :  3.5758223464778425
1000 :  4.34307749919151
1000call :  1.7040201695762516
1000s :  1.41633809712447
100p :  1.7040201695762516
100percent :  1.7040201695762516
100txt :  1.7040201695762516
1030 :  -0.08773929965180294
10am :  2.8026324582443607
10k :  2.1094852776844153
10p :  3.8440863330725223
10ppm :  2.1094852776844153
11 :  1.1650236688435651
1120 :  0.3177258084563608
113 :  1.7040201695762516
114 :  1.7040201695762516
116 :  0.3177258084563608
1172 :  1.7040201695762516
118p :  1.7040201695762516
11mths :  2.8026324582443607
11pm :  1.7040201695762516
12 :  0.4512572010808835
1205 :  0.3177258084563608
120p :  1.7040201695762516
121 :  2.1094852776844153
1225 :  1.7040201695762516
123 :  1.7040201695762516
125 :  1.7040201695762516
1250 :  1.7040201695762516
125gift :  2.1094852776844153
12hours :  1.7040201695762516
12hrs :  3.408768261814677
12mths :  2.1094852776844153
13 :  1.7040201695762516
1327 :  2.397167350136197
139 :  1.7040201695762516
14 :  1.7040201695762516
140 :  0.3177258084563608
1405 :  0.3177258084563608
140ppm :  1.7040201695762516
145 :  1.7040201695762516
1450 :  1.7040201695762516
146tf150p :  1.7040201695762516
14tcr :  1.7040201695762516
14thmarch :  1.7040201695762516
15 :  -0.08773929965180294
150 :  3.495779638804306
1500 :  2.1094852776844153
150p :  4.882073999924197
150pm :  1.7040201695762516
150ppermesssubscription :  2.1094852776844153
150ppm :  4.055395426739729
150ppmpobox10183bhamb64xe :  1.7040201695762516
150pw :  1.7040201695762516
151 :  1.7040201695762516
153 :  2.1094852776844153
15541 :  1.7040201695762516
16 :  3.8142333699228406
165 :  2.1094852776844153
1680 :  0.3177258084563608
169 :  1.7040201695762516
177 :  2.1094852776844153
18 :  4.412070370678462
180 :  0.3177258084563608
1843 :  0.3177258084563608
18p :  1.7040201695762516
18yrs :  2.1094852776844153
195 :  1.7040201695762516
1956669 :  1.7040201695762516
1apple :  0.3177258084563608
1b6a5ecef91ff9 :  1.7040201695762516
1cup :  0.3177258084563608
1er :  1.7040201695762516
1hr :  0.3177258084563608
1im :  0.3177258084563608
1lemon :  0.3177258084563608
1mega :  0.3177258084563608
1million :  1.7040201695762516
1pm :  0.3177258084563608
1st :  1.7040201695762516
1stchoice :  1.7040201695762516
1thing :  0.3177258084563608
1tulsi :  0.3177258084563608
1win150ppmx3 :  1.7040201695762516
1winaweek :  2.1094852776844153
1winawk :  1.7040201695762516
1x150p :  2.397167350136197
1yf :  1.7040201695762516
20 :  1.0108729890163062
200 :  3.0903145306961424
2000 :  3.0903145306961424
2003 :  3.313458082010352
2004 :  3.0903145306961424
2005 :  2.1094852776844153
2007 :  1.7040201695762516
20p :  2.397167350136197
21 :  2.1094852776844153
21870000 :  1.7040201695762516
21st :  1.0108729890163062
22 :  1.0108729890163062
220 :  2.1094852776844153
2309 :  1.7040201695762516
23f :  1.7040201695762516
23g :  1.7040201695762516
24 :  2.620310901450406
24hrs :  1.7040201695762516
24m :  1.7040201695762516
24th :  0.3177258084563608
25 :  1.9271637208904604
250 :  3.649930318631565
250k :  1.7040201695762516
25p :  2.8026324582443607
26 :  1.41633809712447
26th :  1.7040201695762516
27 :  2.1094852776844153
28 :  2.620310901450406
2814032 :  1.7040201695762516
28days :  1.7040201695762516
28th :  1.7040201695762516
29 :  2.1094852776844153
2b :  0.3177258084563608
2bold :  0.3177258084563608
2c :  1.7040201695762516
2day :  -0.08773929965180294
2docd :  0.3177258084563608
2end :  1.7040201695762516
2exit :  1.7040201695762516
2find :  1.7040201695762516
2getha :  0.3177258084563608
2geva :  -0.08773929965180294
2go :  -0.3754213721035846
2i :  0.3177258084563608
2kbsubject :  1.7040201695762516
2lands :  3.208097566352526
2marrow :  -0.08773929965180294
2moro :  0.3177258084563608
2morow :  1.0108729890163062
2morro :  1.0108729890163062
2morrow :  -0.3754213721035846
2morrowxxxx :  0.3177258084563608
2mro :  0.3177258084563608
2mrw :  -0.5985649234177934
2nd :  1.8375515622007743
2nights :  1.7040201695762516
2nite :  1.234016540330515
2optout :  2.8026324582443607
2p :  2.1094852776844153
2price :  1.7040201695762516
2px :  1.7040201695762516
2rcv :  1.7040201695762516
2stop :  1.7040201695762516
2stoptx :  1.7040201695762516
2stoptxt :  2.1094852776844153
2u :  0.3177258084563608
2u2 :  0.3177258084563608
2watershd :  0.3177258084563608
2waxsto :  -0.08773929965180294
2wks :  1.0108729890163062
2wt :  1.7040201695762516
2wu :  1.7040201695762516
2yr :  1.7040201695762516
2yrs :  0.3177258084563608
30 :  -1.4740336607716937
300 :  2.620310901450406
3000 :  1.7040201695762516
300603 :  1.7040201695762516
300603t :  1.7040201695762516
300p :  1.7040201695762516
3030 :  2.620310901450406
30apr :  1.7040201695762516
30ish :  -0.08773929965180294
30pm :  0.3177258084563608
30th :  1.7040201695762516
31 :  2.1094852776844153
3100 :  2.1094852776844153
310303 :  1.7040201695762516
31p :  1.7040201695762516
32000 :  1.7040201695762516
3230 :  0.3177258084563608
32323 :  1.7040201695762516
326 :  1.7040201695762516
33 :  1.7040201695762516
330 :  0.3177258084563608
350 :  3.313458082010352
3510i :  2.397167350136197
35p :  1.7040201695762516
3650 :  1.7040201695762516
36504 :  2.620310901450406
3680 :  1.7040201695762516
373 :  1.7040201695762516
3750 :  1.7040201695762516
37819 :  1.7040201695762516
382 :  0.3177258084563608
391784 :  1.7040201695762516
3aj :  1.7040201695762516
3d :  -0.3754213721035846
3days :  0.3177258084563608
3g :  1.0108729890163062
3gbp :  2.397167350136197
3hrs :  1.7040201695762516
3lions :  1.7040201695762516
3lp :  2.397167350136197
3mins :  2.1094852776844153
3optical :  0.3177258084563608
3pound :  1.7040201695762516
3qxj9 :  2.1094852776844153
3rd :  0.3177258084563608
3ss :  1.7040201695762516
3uz :  2.1094852776844153
3x :  1.7040201695762516
40 :  2.1094852776844153
400 :  2.8026324582443607
400mins :  1.7040201695762516
402 :  1.7040201695762516
4041 :  1.7040201695762516
40411 :  1.7040201695762516
40533 :  1.7040201695762516
40gb :  2.620310901450406
40mph :  0.3177258084563608
41685 :  1.7040201695762516
420 :  0.3177258084563608
4217 :  1.7040201695762516
42478 :  1.7040201695762516
42810 :  1.7040201695762516
430 :  0.3177258084563608
434 :  2.1094852776844153
44 :  1.7040201695762516
440 :  2.1094852776844153
4403ldnw1a7rw18 :  1.7040201695762516
44345 :  1.7040201695762516
447797706009 :  1.7040201695762516
447801259231 :  1.7040201695762516
448712404000 :  1.7040201695762516
449050000301 :  1.7040201695762516
450 :  1.7040201695762516
450p :  1.7040201695762516
450ppw :  1.7040201695762516
450pw :  1.7040201695762516
45239 :  2.1094852776844153
4719 :  1.7040201695762516
4742 :  1.7040201695762516
48 :  -0.08773929965180294
4882 :  1.7040201695762516
48922 :  1.7040201695762516
49 :  1.7040201695762516
49557 :  1.7040201695762516
4a :  -0.08773929965180294
4brekkie :  0.3177258084563608
4d :  0.3177258084563608
4eva :  -0.08773929965180294
4fil :  2.1094852776844153
4get :  -0.08773929965180294
4give :  0.3177258084563608
4got :  0.3177258084563608
4goten :  1.7040201695762516
4info :  2.1094852776844153
4jx :  1.7040201695762516
4msgs :  1.7040201695762516
4mths :  2.1094852776844153
4my :  0.3177258084563608
4qf2 :  1.7040201695762516
4t :  2.397167350136197
4th :  0.3177258084563608
4the :  0.3177258084563608
4thnov :  0.3177258084563608
4txt :  2.1094852776844153
4u :  0.5000473652503157
4ward :  0.3177258084563608
4wrd :  0.3177258084563608
4xx26 :  1.7040201695762516
4years :  0.3177258084563608
50 :  2.7744615812776647
500 :  4.4448601935014524
5000 :  3.5758223464778425
505060 :  1.7040201695762516
50award :  1.7040201695762516
50ea :  1.7040201695762516
50gbp :  2.397167350136197
50p :  2.9567831380716196
50perweeksub :  1.7040201695762516
50perwksub :  2.1094852776844153
50pm :  1.7040201695762516
50pmmorefrommobile2bremoved :  1.7040201695762516
50s :  0.3177258084563608
523 :  1.7040201695762516
5249 :  1.7040201695762516
526 :  1.7040201695762516
528 :  1.7040201695762516
530 :  -0.5985649234177934
54 :  2.1094852776844153
542 :  2.397167350136197
545 :  0.3177258084563608
5digital :  0.3177258084563608
5ish :  0.3177258084563608
5k :  1.7040201695762516
5min :  -0.08773929965180294
5p :  1.7040201695762516
5pm :  0.3177258084563608
5wb :  2.397167350136197
5we :  2.397167350136197
5wkg :  0.3177258084563608
5wq :  1.7040201695762516
5years :  0.3177258084563608
600 :  2.1094852776844153
6031 :  1.7040201695762516
6089 :  1.7040201695762516
60p :  2.397167350136197
61 :  0.3177258084563608
61610 :  1.7040201695762516
6230 :  1.7040201695762516
62468 :  2.620310901450406
62735 :  1.7040201695762516
630 :  0.3177258084563608
63miles :  0.3177258084563608
645 :  0.3177258084563608
65 :  0.3177258084563608
66 :  0.3177258084563608
6669 :  1.7040201695762516
674 :  2.1094852776844153
67441233 :  0.3177258084563608
69200 :  1.7040201695762516
69669 :  2.1094852776844153
69696 :  2.1094852776844153
69876 :  1.7040201695762516
69888 :  2.1094852776844153
69911 :  1.7040201695762516
69969 :  1.7040201695762516
6days :  1.7040201695762516
6hl :  1.7040201695762516
6hrs :  -0.5985649234177934
6ish :  0.3177258084563608
6months :  0.3177258084563608
6ph :  0.3177258084563608
6pm :  0.3177258084563608
6times :  0.3177258084563608
6wu :  1.7040201695762516
6zf :  1.7040201695762516
700 :  -0.08773929965180294
71 :  1.7040201695762516
7250 :  1.7040201695762516
730 :  0.3177258084563608
731 :  1.7040201695762516
74355 :  1.7040201695762516
75 :  1.7040201695762516
750 :  3.7189231901185167
7548 :  1.7040201695762516
762 :  2.1094852776844153
7634 :  1.7040201695762516
7684 :  1.7040201695762516
7732584351 :  1.7040201695762516
78 :  1.7040201695762516
786 :  2.397167350136197
7876150ppm :  1.7040201695762516
79 :  1.7040201695762516
7am :  0.3177258084563608
7cfca1a :  1.7040201695762516
7ish :  -0.08773929965180294
7mp :  1.7040201695762516
7oz :  0.3177258084563608
7pm :  2.1094852776844153
7ws :  1.7040201695762516
7zs :  1.7040201695762516
80 :  1.7040201695762516
800 :  3.5758223464778425
8000930705 :  1.7040201695762516
80062 :  2.620310901450406
8007 :  3.313458082010352
80082 :  1.7040201695762516
80086 :  2.1094852776844153
80122300p :  1.7040201695762516
80155 :  1.7040201695762516
80160 :  1.7040201695762516
8027 :  1.7040201695762516
80488 :  2.397167350136197
80608 :  2.1094852776844153
8077 :  1.7040201695762516
80878 :  2.1094852776844153
81010 :  1.7040201695762516
81151 :  2.397167350136197
81303 :  2.397167350136197
81618 :  2.1094852776844153
82050 :  1.7040201695762516
820554ad0a1705572711 :  1.7040201695762516
82242 :  2.1094852776844153
82277 :  2.620310901450406
82468 :  2.1094852776844153
83021 :  1.7040201695762516
83039 :  1.7040201695762516
83049 :  1.7040201695762516
83110 :  1.7040201695762516
83222 :  2.1094852776844153
83332 :  1.7040201695762516
83338 :  1.7040201695762516
83355 :  2.620310901450406
83383 :  2.1094852776844153
83435 :  1.7040201695762516
83600 :  2.397167350136197
83738 :  1.7040201695762516
84 :  1.7040201695762516
84025 :  1.7040201695762516
84122 :  1.7040201695762516
84128 :  2.1094852776844153
84199 :  1.7040201695762516
84484 :  1.7040201695762516
85 :  2.620310901450406
85023 :  2.1094852776844153
85069 :  1.7040201695762516
85222 :  1.7040201695762516
85233 :  1.7040201695762516
8552 :  2.1094852776844153
85555 :  1.7040201695762516
86021 :  1.7040201695762516
861 :  2.1094852776844153
86688 :  3.495779638804306
86888 :  1.7040201695762516
87021 :  1.7040201695762516
87066 :  3.313458082010352
87070 :  1.7040201695762516
87077 :  3.0903145306961424
87121 :  2.1094852776844153
87131 :  2.620310901450406
8714714 :  1.7040201695762516
872 :  1.7040201695762516
87239 :  2.397167350136197
87575 :  2.1094852776844153
8800 :  1.7040201695762516
88039 :  2.397167350136197
88066 :  2.397167350136197
88088 :  1.7040201695762516

In [65]:
detected = set()
message = "Get free iphone now play this game to win cash prize for free send it to your friends for prize"
for word in message.lower().split():
    if word in spam_scores and spam_scores[word] > 1:
        detected.add(word)

In [66]:
import re
message = re.findall(r"\b\w+\b", message.lower())
message = " ".join(message)
print(message)

get free iphone now play this game to win cash prize for free send it to your friends for prize

In [70]:
print(" ".join(list(detected)))

free prize cash win